export const companyEn = {
  "reports.title": "General reports", "reports.description": "Company-wide financial, sales, inventory, customer, product, and branch reporting with one filter surface.",
  "reports.refresh": "Refresh", "reports.export": "Export CSV", "reports.from": "From", "reports.to": "To", "reports.branch": "Branch", "reports.currency": "Currency",
  "reports.source": "Source", "reports.minimum": "Minimum", "reports.maximum": "Maximum", "reports.sort": "Sort", "reports.search": "Search", "reports.referencePlaceholder": "Reference or description…",
  "reports.allBranches": "All branches", "reports.allSources": "All sources", "reports.onlineOrders": "Online orders", "reports.manualSales": "Manual sales", "reports.purchases": "Purchases",
  "reports.expenses": "Expenses", "reports.payroll": "Payroll", "reports.newest": "Newest first", "reports.oldest": "Oldest first", "reports.highest": "Highest amount", "reports.lowest": "Lowest amount",
  "reports.grossRevenue": "Gross revenue", "reports.cashReceived": "Cash received", "reports.cashPaid": "Cash paid", "reports.netCashFlow": "Net cash flow",
  "reports.operatingBalance": "Operating balance", "reports.receivables": "Customer receivables", "reports.supplierPayables": "Supplier payables", "reports.payrollDue": "Payroll due",
  "reports.businessCoverage": "Business coverage", "reports.products": "products", "reports.customers": "customers", "reports.lowStock": "low stock",
  "reports.cashTrend": "Cash received and paid", "reports.received": "Received", "reports.paid": "Paid", "reports.topProducts": "Top products", "reports.units": "units",
  "reports.noProductSales": "No product sales in this period.", "reports.filteredResult": "Filtered result", "reports.records": "records", "reports.sourceColumn": "Source",
  "reports.reference": "Reference", "reports.date": "Date", "reports.descriptionColumn": "Description", "reports.branchColumn": "Branch", "reports.statusColumn": "Status",
  "reports.amount": "Amount", "reports.paidAmount": "Paid", "reports.balance": "Balance", "reports.company": "Company", "reports.noMatches": "No records match these filters.",
  "reports.page": "Page", "reports.showing": "showing", "reports.previous": "Previous", "reports.next": "Next", "reports.loadError": "Reports could not be loaded.",
  "trash.title": "Trash", "trash.description": "Review deleted records, restore them safely, or permanently purge them. Automatic cleanup follows the company retention setting.",
  "trash.search": "Search deleted item or identifier…", "trash.allTypes": "All record types", "trash.refresh": "Refresh", "trash.empty": "Trash is empty",
  "trash.emptyHelp": "Deleted records will appear here until their retention period expires.", "trash.deleted": "Deleted", "trash.scheduled": "Scheduled purge", "trash.by": "By",
  "trash.restore": "Restore", "trash.deleteForever": "Delete forever", "trash.deleteTitle": "Permanently delete this record?", "trash.deleteDescription": "This action bypasses the trash and cannot be undone.",
  "trash.restored": "Item restored.", "trash.purged": "Item permanently deleted.", "trash.identifier": "ID", "trash.details": "Details", "trash.snapshot": "Saved record snapshot", "trash.noSnapshot": "No readable snapshot is available for this record.",
  "reports.filtersTitle": "Report filters", "reports.filtersHelp": "Filters wrap automatically on mobile, tablet, and desktop.", "reports.resetFilters": "Reset filters",
  "reports.direction": "Direction", "reports.incoming": "Incoming", "reports.outgoing": "Outgoing", "notifications.recentEvents": "Recent admin events", "notifications.activityHelp": "Order, payment, review, and stock activity for this company.", "notifications.live": "Live", "notifications.openedRead": "Opening an item marks the notification as handled in this view.", "notifications.salesActivity": "Sales activity", "notifications.empty": "No notifications", "notifications.emptyHelp": "New company activity will appear here in real time.", "notifications.deleteOne": "Delete notification", "notifications.clearAll": "Clear all", "notifications.deleted": "Notification deleted.", "notifications.cleared": "Notifications cleared.", "notifications.deleteFailed": "Notification could not be deleted.", "notifications.fallback": "Notification", "notifications.retentionDays": "Notification retention days", "notifications.retentionHelp": "Notifications can be removed manually at any time. A background cleanup permanently deletes company notifications older than this number of days."
} as const;

export const companyDr: Record<keyof typeof companyEn, string> = {
  ...companyEn,
  "reports.title": "گزارش‌های عمومی", "reports.description": "گزارش مالی، فروش، موجودی، مشتری، محصول و شعبه در سطح شرکت با یک بخش فیلتر.", "reports.refresh": "تازه‌سازی", "reports.export": "خروجی CSV",
  "reports.from": "از", "reports.to": "تا", "reports.branch": "شعبه", "reports.currency": "ارز", "reports.source": "منبع", "reports.minimum": "کمینه", "reports.maximum": "بیشینه", "reports.sort": "مرتب‌سازی", "reports.search": "جستجو", "reports.referencePlaceholder": "مرجع یا توضیحات…",
  "reports.allBranches": "همه شعبه‌ها", "reports.allSources": "همه منابع", "reports.onlineOrders": "سفارش‌های آنلاین", "reports.manualSales": "فروش دستی", "reports.purchases": "خریدها", "reports.expenses": "مصارف", "reports.payroll": "حقوق",
  "reports.newest": "جدیدترین", "reports.oldest": "قدیمی‌ترین", "reports.highest": "بیشترین مبلغ", "reports.lowest": "کمترین مبلغ", "reports.grossRevenue": "درآمد ناخالص", "reports.cashReceived": "وجه دریافت‌شده", "reports.cashPaid": "وجه پرداخت‌شده", "reports.netCashFlow": "جریان نقدی خالص",
  "reports.operatingBalance": "تراز عملیاتی", "reports.receivables": "مطالبات مشتری", "reports.supplierPayables": "بدهی تأمین‌کننده", "reports.payrollDue": "حقوق باقی‌مانده", "reports.businessCoverage": "پوشش کسب‌وکار", "reports.products": "محصول", "reports.customers": "مشتری", "reports.lowStock": "کم‌موجود",
  "reports.cashTrend": "وجه دریافت و پرداخت", "reports.received": "دریافت", "reports.paid": "پرداخت", "reports.topProducts": "محصولات برتر", "reports.units": "واحد", "reports.noProductSales": "در این دوره فروشی ثبت نشده است.", "reports.filteredResult": "نتیجه فیلترشده", "reports.records": "رکورد",
  "reports.sourceColumn": "منبع", "reports.reference": "مرجع", "reports.date": "تاریخ", "reports.descriptionColumn": "توضیحات", "reports.branchColumn": "شعبه", "reports.statusColumn": "وضعیت", "reports.amount": "مبلغ", "reports.paidAmount": "پرداخت", "reports.balance": "باقی‌مانده", "reports.company": "شرکت",
  "reports.noMatches": "رکوردی مطابق فیلترها نیست.", "reports.page": "صفحه", "reports.showing": "نمایش", "reports.previous": "قبلی", "reports.next": "بعدی", "reports.loadError": "گزارش‌ها بارگذاری نشد.",
  "trash.title": "زباله‌دان", "trash.description": "رکوردهای حذف‌شده را بررسی، بازیابی یا برای همیشه پاک کنید. پاک‌سازی خودکار بر اساس تنظیم شرکت است.", "trash.search": "جستجوی مورد حذف‌شده یا شناسه…", "trash.allTypes": "همه نوع رکورد", "trash.refresh": "تازه‌سازی", "trash.empty": "زباله‌دان خالی است", "trash.emptyHelp": "رکوردهای حذف‌شده تا پایان مدت نگهداری اینجا نمایش داده می‌شوند.",
  "trash.deleted": "حذف‌شده", "trash.scheduled": "پاک‌سازی برنامه‌ریزی‌شده", "trash.by": "توسط", "trash.restore": "بازیابی", "trash.deleteForever": "حذف همیشگی", "trash.deleteTitle": "این رکورد برای همیشه حذف شود؟", "trash.deleteDescription": "این کار قابل بازگشت نیست.", "trash.restored": "مورد بازیابی شد.", "trash.purged": "مورد برای همیشه حذف شد.", "trash.identifier": "شناسه", "trash.details": "جزئیات", "trash.snapshot": "نسخه ذخیره‌شده رکورد", "trash.noSnapshot": "برای این رکورد نسخه قابل خواندن موجود نیست.",
  "reports.filtersTitle": "فیلترهای گزارش", "reports.filtersHelp": "فیلترها در موبایل، تبلت و دسکتاپ به‌صورت خودکار تنظیم می‌شوند.", "reports.resetFilters": "پاک‌کردن فیلترها",
  "reports.direction": "جهت", "reports.incoming": "ورودی", "reports.outgoing": "خروجی", "notifications.recentEvents": "رویدادهای اخیر مدیریت", "notifications.activityHelp": "فعالیت سفارش، پرداخت، نظر و موجودی این شرکت.", "notifications.live": "زنده", "notifications.openedRead": "باز کردن مورد، آن را در این نما رسیدگی‌شده می‌سازد.", "notifications.salesActivity": "فعالیت فروش", "notifications.empty": "اعلانی وجود ندارد", "notifications.emptyHelp": "فعالیت جدید شرکت به‌صورت زنده اینجا نمایش داده می‌شود.", "notifications.deleteOne": "حذف اعلان", "notifications.clearAll": "پاک‌کردن همه", "notifications.deleted": "اعلان حذف شد.", "notifications.cleared": "اعلان‌ها پاک شدند.", "notifications.deleteFailed": "اعلان حذف نشد.", "notifications.fallback": "اعلان", "notifications.retentionDays": "روزهای نگهداری اعلان", "notifications.retentionHelp": "اعلان‌ها هر زمان به‌صورت دستی قابل حذف اند. پاک‌سازی پس‌زمینه اعلان‌های قدیمی‌تر از این تعداد روز را برای همیشه حذف می‌کند."
};

export const companyPs: Record<keyof typeof companyEn, string> = {
  ...companyEn,
  "reports.title": "عمومي راپورونه", "reports.description": "د شرکت په کچه مالي، پلور، موجودي، پېرېدونکي، محصول او څانګو راپورونه له یوه فلټر څخه.", "reports.refresh": "نوي کول", "reports.export": "CSV صادرول", "reports.from": "له", "reports.to": "تر", "reports.branch": "څانګه", "reports.currency": "اسعار", "reports.source": "سرچینه", "reports.minimum": "لږ تر لږه", "reports.maximum": "زیات تر زیات", "reports.sort": "ترتیب", "reports.search": "لټون", "reports.referencePlaceholder": "مرجع یا تشریح…", "reports.allBranches": "ټولې څانګې", "reports.allSources": "ټولې سرچینې", "reports.onlineOrders": "آنلاین فرمایشونه", "reports.manualSales": "لاسي پلور", "reports.purchases": "پېرودونه", "reports.expenses": "لګښتونه", "reports.payroll": "معاشونه", "reports.newest": "نوي لومړی", "reports.oldest": "زاړه لومړی", "reports.highest": "لوړ مبلغ", "reports.lowest": "ټیټ مبلغ", "reports.grossRevenue": "ناخالص عاید", "reports.cashReceived": "ترلاسه شوې پیسې", "reports.cashPaid": "ورکړل شوې پیسې", "reports.netCashFlow": "خالص نغدي جریان", "reports.operatingBalance": "عملیاتي بیلانس", "reports.receivables": "د پېرېدونکو پاتې", "reports.supplierPayables": "د عرضه کوونکو پاتې", "reports.payrollDue": "پاتې معاش", "reports.businessCoverage": "د سوداګرۍ پوښښ", "reports.products": "محصولات", "reports.customers": "پېرېدونکي", "reports.lowStock": "کم موجودي", "reports.cashTrend": "ترلاسه او ورکړل شوې پیسې", "reports.received": "ترلاسه", "reports.paid": "ورکړل", "reports.topProducts": "غوره محصولات", "reports.units": "واحدونه", "reports.noProductSales": "په دې موده کې پلور نشته.", "reports.filteredResult": "فلټر شوې پایله", "reports.records": "ریکارډونه", "reports.sourceColumn": "سرچینه", "reports.reference": "مرجع", "reports.date": "نېټه", "reports.descriptionColumn": "تشریح", "reports.branchColumn": "څانګه", "reports.statusColumn": "حالت", "reports.amount": "مبلغ", "reports.paidAmount": "ورکړل شوي", "reports.balance": "پاتې", "reports.company": "شرکت", "reports.noMatches": "له فلټر سره سم ریکارډ نشته.", "reports.page": "پاڼه", "reports.showing": "ښودل", "reports.previous": "مخکینی", "reports.next": "بل", "reports.loadError": "راپورونه پورته نه شول.",
  "trash.title": "کثافات", "trash.description": "ړنګ شوي ریکارډونه وګورئ، بېرته یې راولئ یا تل لپاره یې پاک کړئ. اتومات پاکول د شرکت د تنظیم له مخې دي.", "trash.search": "ړنګ شوی توکی یا پېژند ولټوئ…", "trash.allTypes": "د ریکارډ ټول ډولونه", "trash.refresh": "نوي کول", "trash.empty": "کثافات تش دي", "trash.emptyHelp": "ړنګ شوي ریکارډونه د ساتنې تر مودې دلته ښکاري.", "trash.deleted": "ړنګ شوی", "trash.scheduled": "ټاکل شوی پاکول", "trash.by": "د", "trash.restore": "بېرته راوستل", "trash.deleteForever": "تل لپاره ړنګول", "trash.deleteTitle": "دا ریکارډ تل لپاره ړنګ شي؟", "trash.deleteDescription": "دا کار بېرته نه راګرځي.", "trash.restored": "توکی بېرته راوستل شو.", "trash.purged": "توکی تل لپاره ړنګ شو.", "trash.identifier": "پېژند", "trash.details": "جزئیات", "trash.snapshot": "د ریکارډ خوندي شوې بڼه", "trash.noSnapshot": "د دې ریکارډ لپاره د لوستلو وړ بڼه نشته.",
  "reports.filtersTitle": "د راپور فلټرونه", "reports.filtersHelp": "فلټرونه په موبایل، ټابلیټ او ډیسکتاپ کې په اوتومات ډول برابرېږي.", "reports.resetFilters": "فلټرونه پاک کړئ",
  "reports.direction": "لوری", "reports.incoming": "راتلونکی", "reports.outgoing": "وتونکی", "notifications.recentEvents": "وروستي اداري پېښې", "notifications.activityHelp": "د دې شرکت د فرمایش، تادیې، بیاکتنې او موجودۍ فعالیت.", "notifications.live": "ژوندی", "notifications.openedRead": "د توکي پرانیستل یې په دې لید کې د رسېدلي په توګه ښيي.", "notifications.salesActivity": "د پلور فعالیت", "notifications.empty": "خبرتیا نشته", "notifications.emptyHelp": "د شرکت نوی فعالیت به دلته ژوندی ښکاره شي.", "notifications.deleteOne": "خبرتیا ړنګول", "notifications.clearAll": "ټولې پاکې کړئ", "notifications.deleted": "خبرتیا ړنګه شوه.", "notifications.cleared": "خبرتیاوې پاکې شوې.", "notifications.deleteFailed": "خبرتیا ړنګه نه شوه.", "notifications.fallback": "خبرتیا", "notifications.retentionDays": "د خبرتیا ساتنې ورځې", "notifications.retentionHelp": "خبرتیا هر وخت لاسي ړنګېدای شي. شالید پاکوونکی له ټاکلو ورځو زاړه خبرتیاوې تل لپاره ړنګوي."
};
