import type { en } from "./en";
import { inventoryDr } from "@/features/inventory/i18n/inventory-translations";
import { pricingDr } from "@/features/products/i18n/pricing-translations";
export const dr: Record<keyof typeof en, string> = {
  "language.en": "انگلیسی", "language.ps": "پشتو", "language.dr": "دری",
  "common.profile": "پروفایل", "common.logout": "خروج", "common.notifications": "اعلان‌ها",
  "dashboard.subtitle": "نمای کلی فعالیت و عملکرد فروشگاه شما.", "create.title": "ایجاد محصول", "create.subtitle": "یک محصول جدید به فهرست خود اضافه کنید.", "create.back": "بازگشت",
  "nav.platform": "پلتفرم", "nav.dashboard": "داشبورد", "nav.products": "محصولات", "nav.allProducts": "همه محصولات", "nav.categories": "دسته‌بندی‌ها", "nav.brands": "برندها", "nav.units": "واحدها", "nav.inventory": "موجودی", "nav.stockOverview": "نمای کلی موجودی", "nav.stockTransactions": "تراکنش‌های موجودی", "nav.lowStock": "موجودی کم", "nav.orders": "سفارش‌ها", "nav.allOrders": "همه سفارش‌ها", "nav.pendingOrders": "سفارش‌های در انتظار", "nav.completedOrders": "سفارش‌های تکمیل‌شده", "nav.cancelledOrders": "سفارش‌های لغوشده", "nav.customers": "مشتریان", "nav.allCustomers": "همه مشتریان", "nav.customerTypes": "انواع مشتری", "nav.system": "سیستم", "nav.generalTypes": "انواع عمومی", "nav.users": "کاربران", "nav.roles": "نقش‌ها و دسترسی‌ها",
  "products.title": "محصولات", "products.subtitle": "محصولات فروشگاه را مدیریت کنید", "products.navigation": "صفحه‌های محصولات", "products.updateSelected": "به‌روزرسانی انتخاب‌شده‌ها", "products.bulkCreate": "ایجاد گروهی", "products.search": "جستجو با نام یا بارکد...", "products.product": "محصول", "products.barcode": "بارکد", "products.category": "دسته‌بندی", "products.price": "قیمت", "products.stock": "موجودی", "products.status": "وضعیت", "products.active": "فعال", "products.inactive": "غیرفعال", "products.empty": "محصولی یافت نشد.", "products.loadError": "محصولات بارگذاری نشدند.", "products.refreshing": "محصولات تازه‌سازی می‌شوند...",
  "filters.title": "فیلترها", "filters.description": "فهرست محصولات را بر اساس اطلاعات کاتالوگ، وضعیت، قیمت و ترتیب محدود کنید.", "filters.all": "همه", "filters.yes": "بله", "filters.no": "خیر", "filters.featured": "ویژه", "filters.sort": "مرتب‌سازی", "filters.newest": "جدیدترین", "filters.oldest": "قدیمی‌ترین", "filters.nameAsc": "نام الف–ی", "filters.nameDesc": "نام ی–الف", "filters.priceAsc": "قیمت: کم به زیاد", "filters.priceDesc": "قیمت: زیاد به کم", "filters.minPrice": "حداقل قیمت", "filters.maxPrice": "حداکثر قیمت", "filters.clear": "پاک‌کردن فیلترها", "filters.removeAll": "حذف فیلترها", "filters.apply": "اعمال فیلترها", "filters.clearSearch": "پاک‌کردن جستجو",
  "pagination.showing": "نمایش", "pagination.of": "از", "pagination.rows": "سطر در هر صفحه", "pagination.previous": "صفحه قبلی", "pagination.next": "صفحه بعدی", "pagination.page": "صفحه",
  "form.name": "نام", "form.parent": "والد", "form.save": "ذخیره", "form.cancel": "لغو", "form.description": "توضیحات", "form.shortDescription": "توضیح کوتاه", "form.slug": "نامک", "form.minimum": "حداقل مقدار", "form.maximum": "حداکثر مقدار", "form.brand": "برند", "form.unit": "واحد", "form.none": "هیچ‌کدام", "form.search": "جستجو", "form.noMatch": "گزینه‌ای یافت نشد.",
  "bulk.title": "ایجاد گروهی محصولات", "bulk.subtitle": "چند تصویر انتخاب کرده و اطلاعات هر محصول را وارد کنید.", "bulk.clear": "پاک‌کردن همه", "bulk.noProducts": "محصولی انتخاب نشده", "bulk.selectImages": "برای ساخت فرم‌ها تصاویر محصولات را انتخاب کنید.", "bulk.ready": "آماده", "bulk.submitTogether": "همه محصولات باهم ارسال می‌شوند.", "bulk.create": "ایجاد", "bulk.creating": "در حال ایجاد محصولات...", "bulk.productName": "نام محصول", "bulk.replaceImage": "تغییر تصویر", "bulk.activeProduct": "محصول فعال", "bulk.activeHelp": "محصول در سیستم قابل استفاده است.", "bulk.featuredProduct": "محصول ویژه", "bulk.featuredHelp": "محصول را در بخش‌های ویژه نمایش دهید.",
  "uploader.drop": "تصاویر را اینجا رها کنید", "uploader.title": "بارگذاری تصاویر محصول", "uploader.instructions": "تصاویر را اینجا بکشید، از دستگاه انتخاب کنید یا تصاویر کپی‌شده را بچسبانید.", "uploader.pasteBefore": "روی این بخش کلیک کنید، سپس فشار دهید", "uploader.pasteAfter": "برای چسباندن.", "uploader.formats": "JPG، PNG، WEBP یا AVIF. حداکثر ۵ MB برای هر تصویر.", "uploader.choose": "انتخاب تصاویر",
  "update.title": "به‌روزرسانی محصول", "update.bulkTitle": "به‌روزرسانی گروهی محصولات", "update.subtitle": "تمام اطلاعات محصول را به‌روزرسانی کنید و در صورت نیاز تصویر اصلی را تغییر دهید. همه تغییرات باهم ارسال می‌شوند.", "update.close": "بستن ویرایشگر", "update.untitled": "بدون نام", "update.replaceImage": "تغییر تصویر", "update.keepImage": "برای نگه‌داشتن تصویر فعلی، خالی بگذارید.", "update.galleryImages": "تصاویر گالری", "update.galleryHelp": "برای این محصول انتخاب‌شده تصاویر فرعی اضافه کنید.", "update.addGalleryImages": "افزودن تصاویر گالری", "update.removeGalleryImage": "حذف تصویر گالری", "update.galleryLimit": "هر محصول می‌تواند حداکثر ۱۰ تصویر داشته باشد.", "update.productNumber": "محصول", "update.category": "دسته‌بندی", "update.barcode": "بارکد", "update.searchOption": "جستجو در گزینه‌ها...", "update.noMatch": "گزینه‌ای یافت نشد.", "update.activeHelp": "محصول برای استفاده در فروشگاه در دسترس است.", "update.featuredHelp": "محصول را در بخش‌های ویژه نمایش دهید.", "update.previous": "قبلی", "update.next": "بعدی", "update.submit": "به‌روزرسانی محصولات", "update.submitting": "در حال به‌روزرسانی محصولات...", "update.success": "محصولات با موفقیت به‌روزرسانی شدند.", "update.connectionError": "اتصال به API محصولات ممکن نیست. بخش پشتی را دوباره راه‌اندازی و تلاش کنید.", "update.endpointError": "بخش پشتی از مسیر قدیمی به‌روزرسانی استفاده می‌کند. آن را دوباره راه‌اندازی و تلاش کنید.", "update.failed": "به‌روزرسانی محصول ناموفق بود.",
  "types.title": "انواع عمومی", "types.subtitle": "دسته‌بندی‌ها، برندها، واحدها و انواع مشتری قابل استفاده مجدد را مدیریت کنید.", "types.add": "افزودن نوع", "types.create": "ایجاد نوع عمومی", "types.edit": "ویرایش نوع عمومی", "types.group": "گروه", "types.actions": "عملیات", "types.all": "همه انواع", "types.category": "دسته‌بندی‌ها", "types.brand": "برندها", "types.unit": "واحدها", "types.customerType": "انواع مشتری", "types.unknownGroup": "سایر", "types.search": "جستجوی انواع...", "types.refresh": "تازه‌سازی انواع", "types.loading": "در حال بارگذاری انواع...", "types.loadError": "انواع بارگذاری نشدند.", "types.retry": "تلاش دوباره", "types.empty": "نوعی یافت نشد", "types.emptyHelp": "فیلترها را تغییر دهید یا نوع جدیدی اضافه کنید.", "types.noParent": "بدون والد (سطح بالا)", "types.saving": "در حال ذخیره...", "types.created": "نوع با موفقیت ایجاد شد.", "types.updated": "نوع با موفقیت به‌روزرسانی شد.", "types.saveError": "نوع ذخیره نشد.", "types.delete": "حذف", "types.deleting": "در حال حذف نوع...", "types.deleted": "نوع با موفقیت حذف شد.", "types.deleteError": "این نوع حذف نشد. ابتدا زیرمجموعه‌ها یا اطلاعات مرتبط را حذف کنید.", "types.deleteTitle": "این نوع حذف شود؟", "types.deleteDescription": "این عمل قابل بازگشت نیست. انواع دارای زیرمجموعه یا اطلاعات مرتبط قابل حذف نیستند.",
  "update.savedImage": "ذخیره‌شده", "update.newImage": "جدید",
  "products.deleteSelected": "حذف انتخاب‌شده‌ها", "products.deleteTitle": "محصولات انتخاب‌شده حذف شوند؟", "products.deleteDescription": "محصولات انتخاب‌شده از فهرست حذف می‌شوند. این عمل از پنل مدیریت قابل بازگشت نیست.", "products.confirmDelete": "حذف محصولات", "products.deleting": "در حال حذف محصولات...", "products.deleteSuccess": "محصولات با موفقیت حذف شدند.", "products.deleteError": "محصولات انتخاب‌شده حذف نشدند.",
  "details.subtitle": "اطلاعات کامل محصول، تصاویر، موجودی و قیمت‌ها.", "details.back": "بازگشت به محصولات", "details.open": "مشاهده جزئیات محصول", "details.notFound": "محصول یافت نشد", "details.notFoundHelp": "این محصول ممکن است حذف شده یا در دسترس نباشد.", "details.featured": "ویژه", "details.noDescription": "برای این محصول توضیحی ثبت نشده است.", "details.views": "بازدیدها", "details.created": "تاریخ ایجاد", "details.updated": "آخرین به‌روزرسانی", "details.inventory": "موجودی", "details.totalStock": "موجودی کل", "details.availableStock": "موجودی قابل دسترس", "details.reservedStock": "موجودی رزرو", "details.minimumStock": "حداقل موجودی", "details.expiry": "تاریخ انقضا", "details.pricing": "قیمت‌گذاری", "details.noPrices": "قیمتی برای مشتریان تنظیم نشده است.",
  "types.image": "تصویر", "types.imageUrl": "نشانی تصویر", "types.imageUrlHelp": "یک نشانی عمومی HTTP یا HTTPS برای تصویر وارد کنید.", "types.useImage": "استفاده از تصویر", "types.useImageHelp": "اختیاری است. فقط زمانی فعال کنید که این نوع به تصویر نیاز دارد.", "types.imageSource": "منبع تصویر", "types.uploadImage": "بارگذاری تصویر", "types.onlineUrl": "نشانی آنلاین", "types.chooseImage": "انتخاب تصویر از دستگاه", "types.imageFileHelp": "JPG، PNG، WEBP یا AVIF، حداکثر ۵ مگابایت.", "types.imagePreview": "پیش‌نمایش تصویر نوع", "types.removeImage": "حذف تصویر", "types.imageFormatError": "یک تصویر معتبر JPG، PNG، WEBP یا AVIF انتخاب کنید.", "types.imageSizeError": "اندازه تصویر نباید بیشتر از ۵ مگابایت باشد.", "types.imageUrlError": "یک نشانی معتبر HTTP یا HTTPS وارد کنید.", "types.imageRequired": "پیش از ذخیره تصویر انتخاب کنید یا گزینه تصویر را غیرفعال کنید.",
  ...inventoryDr,
  ...pricingDr,
};
