import type { en } from "./en";
export const dr: Record<keyof typeof en, string> = {
  "language.en": "انگلیسی", "language.ps": "پشتو", "language.dr": "دری",
  "common.profile": "پروفایل", "common.logout": "خروج", "common.notifications": "اعلان‌ها",
  "dashboard.subtitle": "نمای کلی فعالیت و عملکرد فروشگاه شما.", "create.title": "ایجاد محصول", "create.subtitle": "یک محصول جدید به فهرست خود اضافه کنید.", "create.back": "بازگشت",
  "nav.platform": "پلتفرم", "nav.dashboard": "داشبورد", "nav.products": "محصولات", "nav.allProducts": "همه محصولات", "nav.categories": "دسته‌بندی‌ها", "nav.brands": "برندها", "nav.units": "واحدها", "nav.inventory": "موجودی", "nav.stockOverview": "نمای کلی موجودی", "nav.stockTransactions": "تراکنش‌های موجودی", "nav.lowStock": "موجودی کم", "nav.orders": "سفارش‌ها", "nav.allOrders": "همه سفارش‌ها", "nav.pendingOrders": "سفارش‌های در انتظار", "nav.completedOrders": "سفارش‌های تکمیل‌شده", "nav.cancelledOrders": "سفارش‌های لغوشده", "nav.customers": "مشتریان", "nav.allCustomers": "همه مشتریان", "nav.customerTypes": "انواع مشتری", "nav.system": "سیستم", "nav.generalTypes": "انواع عمومی", "nav.users": "کاربران", "nav.roles": "نقش‌ها و دسترسی‌ها",
  "products.title": "محصولات", "products.subtitle": "محصولات فروشگاه را مدیریت کنید", "products.updateSelected": "به‌روزرسانی انتخاب‌شده‌ها", "products.bulkCreate": "ایجاد گروهی", "products.search": "جستجو با نام یا بارکد...", "products.product": "محصول", "products.barcode": "بارکد", "products.category": "دسته‌بندی", "products.price": "قیمت", "products.stock": "موجودی", "products.status": "وضعیت", "products.active": "فعال", "products.inactive": "غیرفعال", "products.empty": "محصولی یافت نشد.", "products.loadError": "محصولات بارگذاری نشدند.",
  "form.name": "نام", "form.parent": "والد", "form.save": "ذخیره", "form.cancel": "لغو", "form.description": "توضیحات", "form.shortDescription": "توضیح کوتاه", "form.slug": "نامک", "form.minimum": "حداقل مقدار", "form.maximum": "حداکثر مقدار", "form.brand": "برند", "form.unit": "واحد", "form.none": "هیچ‌کدام", "form.search": "جستجو", "form.noMatch": "گزینه‌ای یافت نشد.",
  "bulk.title": "ایجاد گروهی محصولات", "bulk.subtitle": "چند تصویر انتخاب کرده و اطلاعات هر محصول را وارد کنید.", "bulk.clear": "پاک‌کردن همه", "bulk.noProducts": "محصولی انتخاب نشده", "bulk.selectImages": "برای ساخت فرم‌ها تصاویر محصولات را انتخاب کنید.", "bulk.ready": "آماده", "bulk.submitTogether": "همه محصولات باهم ارسال می‌شوند.", "bulk.create": "ایجاد", "bulk.creating": "در حال ایجاد محصولات...", "bulk.productName": "نام محصول", "bulk.replaceImage": "تغییر تصویر", "bulk.activeProduct": "محصول فعال", "bulk.activeHelp": "محصول در سیستم قابل استفاده است.", "bulk.featuredProduct": "محصول ویژه", "bulk.featuredHelp": "محصول را در بخش‌های ویژه نمایش دهید.",
  "uploader.drop": "تصاویر را اینجا رها کنید", "uploader.title": "بارگذاری تصاویر محصول", "uploader.instructions": "تصاویر را اینجا بکشید، از دستگاه انتخاب کنید یا تصاویر کپی‌شده را بچسبانید.", "uploader.pasteBefore": "روی این بخش کلیک کنید، سپس فشار دهید", "uploader.pasteAfter": "برای چسباندن.", "uploader.formats": "JPG، PNG یا WEBP. حداکثر ۵ MB برای هر تصویر.", "uploader.choose": "انتخاب تصاویر",
  "update.title": "به‌روزرسانی محصول", "update.bulkTitle": "به‌روزرسانی گروهی محصولات", "update.subtitle": "تمام اطلاعات محصول را به‌روزرسانی کنید و در صورت نیاز تصویر اصلی را تغییر دهید. همه تغییرات باهم ارسال می‌شوند.", "update.close": "بستن ویرایشگر", "update.untitled": "بدون نام", "update.replaceImage": "تغییر تصویر", "update.keepImage": "برای نگه‌داشتن تصویر فعلی، خالی بگذارید.", "update.productNumber": "محصول", "update.category": "دسته‌بندی", "update.barcode": "بارکد", "update.searchOption": "جستجو در گزینه‌ها...", "update.noMatch": "گزینه‌ای یافت نشد.", "update.activeHelp": "محصول برای استفاده در فروشگاه در دسترس است.", "update.featuredHelp": "محصول را در بخش‌های ویژه نمایش دهید.", "update.previous": "قبلی", "update.next": "بعدی", "update.submit": "به‌روزرسانی محصولات", "update.submitting": "در حال به‌روزرسانی محصولات...", "update.success": "محصولات با موفقیت به‌روزرسانی شدند.", "update.connectionError": "اتصال به API محصولات ممکن نیست. بخش پشتی را دوباره راه‌اندازی و تلاش کنید.", "update.endpointError": "بخش پشتی از مسیر قدیمی به‌روزرسانی استفاده می‌کند. آن را دوباره راه‌اندازی و تلاش کنید.", "update.failed": "به‌روزرسانی محصول ناموفق بود.",
  "types.title": "انواع عمومی", "types.subtitle": "انواع عمومی فروشگاه را مدیریت کنید", "types.add": "افزودن نوع", "types.create": "ایجاد نوع عمومی", "types.edit": "ویرایش نوع عمومی", "types.group": "گروه", "types.actions": "عملیات",
};
