import { inventoryEn } from "@/features/inventory/i18n/inventory-translations";
import { pricingEn } from "@/features/products/i18n/pricing-translations";

export const en = {
  "language.en": "English", "language.ps": "Pashto", "language.dr": "Dari",
  "common.profile": "Profile", "common.logout": "Log out", "common.notifications": "Notifications",
  "dashboard.subtitle": "Overview of your store activity and performance.", "create.title": "Create product", "create.subtitle": "Add a new product to your catalog.", "create.back": "Back",
  "nav.platform": "Platform", "nav.dashboard": "Dashboard", "nav.products": "Products", "nav.allProducts": "All Products", "nav.categories": "Categories", "nav.brands": "Brands", "nav.units": "Units", "nav.inventory": "Inventory", "nav.stockOverview": "Stock Overview", "nav.stockTransactions": "Stock Transactions", "nav.lowStock": "Low Stock", "nav.orders": "Orders", "nav.allOrders": "All Orders", "nav.pendingOrders": "Pending Orders", "nav.completedOrders": "Completed Orders", "nav.cancelledOrders": "Cancelled Orders", "nav.customers": "Customers", "nav.allCustomers": "All Customers", "nav.customerTypes": "Customer Types", "nav.system": "System", "nav.generalTypes": "General Types", "nav.users": "Users", "nav.roles": "Roles & Permissions",
  "products.title": "Products", "products.subtitle": "Manage your store products", "products.navigation": "Product pages", "products.updateSelected": "Update selected", "products.bulkCreate": "Bulk create", "products.search": "Search by name or barcode...", "products.product": "Product", "products.barcode": "Barcode", "products.category": "Category", "products.price": "Price", "products.stock": "Stock", "products.status": "Status", "products.active": "Active", "products.inactive": "Inactive", "products.empty": "No products found.", "products.loadError": "Products could not be loaded.", "products.refreshing": "Refreshing products...",
  "filters.title": "Filters", "filters.description": "Narrow the product list by catalog details, status, price, and sorting.", "filters.all": "All", "filters.yes": "Yes", "filters.no": "No", "filters.featured": "Featured", "filters.sort": "Sort by", "filters.newest": "Newest first", "filters.oldest": "Oldest first", "filters.nameAsc": "Name A–Z", "filters.nameDesc": "Name Z–A", "filters.priceAsc": "Price: low to high", "filters.priceDesc": "Price: high to low", "filters.minPrice": "Minimum price", "filters.maxPrice": "Maximum price", "filters.clear": "Clear filters", "filters.removeAll": "Remove filters", "filters.apply": "Apply filters", "filters.clearSearch": "Clear search",
  "pagination.showing": "Showing", "pagination.of": "of", "pagination.rows": "Rows per page", "pagination.previous": "Previous page", "pagination.next": "Next page", "pagination.page": "Page",
  "form.name": "Name", "form.parent": "Parent", "form.save": "Save", "form.cancel": "Cancel", "form.description": "Description", "form.shortDescription": "Short description", "form.slug": "Slug", "form.minimum": "Minimum value", "form.maximum": "Maximum value", "form.brand": "Brand", "form.unit": "Unit", "form.none": "None", "form.search": "Search", "form.noMatch": "No matching option.",
  "bulk.title": "Bulk product creation", "bulk.subtitle": "Select multiple images and enter the information for each product.", "bulk.clear": "Clear all", "bulk.noProducts": "No products selected", "bulk.selectImages": "Select product images to generate the forms.", "bulk.ready": "ready", "bulk.submitTogether": "All products will be submitted together.", "bulk.create": "Create", "bulk.creating": "Creating products...", "bulk.productName": "Product name", "bulk.replaceImage": "Replace image", "bulk.activeProduct": "Active product", "bulk.activeHelp": "Product can be used in the system.", "bulk.featuredProduct": "Featured product", "bulk.featuredHelp": "Display this product as featured.",
  "uploader.drop": "Drop images here", "uploader.title": "Upload product images", "uploader.instructions": "Drag and drop images here, choose them from your device, or paste copied images.", "uploader.pasteBefore": "Click this area, then press", "uploader.pasteAfter": "to paste.", "uploader.formats": "JPG, PNG, WEBP or AVIF. Maximum 5 MB per image.", "uploader.choose": "Choose images",
  "update.title": "Update product", "update.bulkTitle": "Bulk update products", "update.subtitle": "Update every product field and optionally replace its primary image. All changes are submitted together.", "update.close": "Close editor", "update.untitled": "Untitled", "update.replaceImage": "Replace image", "update.keepImage": "Leave empty to keep the current image.", "update.galleryImages": "Gallery images", "update.galleryHelp": "Add secondary images for this selected product.", "update.addGalleryImages": "Add gallery images", "update.removeGalleryImage": "Remove gallery image", "update.galleryLimit": "A product can have a maximum of 10 images.", "update.productNumber": "Product", "update.category": "Category", "update.barcode": "Barcode", "update.searchOption": "Search options...", "update.noMatch": "No matching option.", "update.activeHelp": "Product is available for use in the store.", "update.featuredHelp": "Highlight this product in featured sections.", "update.previous": "Previous", "update.next": "Next", "update.submit": "Update products", "update.submitting": "Updating products...", "update.success": "Products updated successfully.", "update.connectionError": "Cannot connect to the product API. Restart the backend and try again.", "update.endpointError": "The backend is running an older update endpoint. Restart it and try again.", "update.failed": "Product update failed.",
  "types.title": "General Types", "types.subtitle": "Manage reusable categories, brands, units, and customer types.", "types.add": "Add type", "types.create": "Create general type", "types.edit": "Edit general type", "types.group": "Group", "types.actions": "Actions", "types.all": "All types", "types.category": "Categories", "types.brand": "Brands", "types.unit": "Units", "types.customerType": "Customer types", "types.unknownGroup": "Other", "types.search": "Search types...", "types.refresh": "Refresh types", "types.loading": "Loading types...", "types.loadError": "Types could not be loaded.", "types.retry": "Try again", "types.empty": "No types found", "types.emptyHelp": "Change the filters or add a new type.", "types.noParent": "No parent (top level)", "types.saving": "Saving...", "types.created": "Type created successfully.", "types.updated": "Type updated successfully.", "types.saveError": "The type could not be saved.", "types.delete": "Delete", "types.deleting": "Deleting type...", "types.deleted": "Type deleted successfully.", "types.deleteError": "This type could not be deleted. Remove its children or linked records first.", "types.deleteTitle": "Delete this type?", "types.deleteDescription": "This cannot be undone. Types with children or linked records cannot be deleted.",
  "update.savedImage": "Saved", "update.newImage": "New",
  "products.deleteSelected": "Delete selected", "products.deleteTitle": "Delete selected products?", "products.deleteDescription": "The selected products will be removed from the catalog. This action cannot be undone from the admin panel.", "products.confirmDelete": "Delete products", "products.deleting": "Deleting products...", "products.deleteSuccess": "Products deleted successfully.", "products.deleteError": "The selected products could not be deleted.",
  "details.subtitle": "Complete product information, media, inventory and pricing.", "details.back": "Back to products", "details.open": "View product details", "details.notFound": "Product not found", "details.notFoundHelp": "This product may have been removed or is unavailable.", "details.featured": "Featured", "details.noDescription": "No description has been added for this product.", "details.views": "Views", "details.created": "Created", "details.updated": "Last updated", "details.inventory": "Inventory", "details.totalStock": "Total stock", "details.availableStock": "Available stock", "details.reservedStock": "Reserved stock", "details.minimumStock": "Minimum stock", "details.expiry": "Expiry date", "details.pricing": "Pricing", "details.noPrices": "No customer pricing has been configured.",
  "types.image": "Image", "types.imageUrl": "Image URL", "types.imageUrlHelp": "Enter a public HTTP or HTTPS image URL.", "types.useImage": "Use an image", "types.useImageHelp": "Optional. Enable this only when the type needs a visual image.", "types.imageSource": "Image source", "types.uploadImage": "Upload image", "types.onlineUrl": "Online URL", "types.chooseImage": "Choose an image from your device", "types.imageFileHelp": "JPG, PNG, WEBP or AVIF, up to 5 MB.", "types.imagePreview": "Type image preview", "types.removeImage": "Remove image", "types.imageFormatError": "Choose a valid JPG, PNG, WEBP or AVIF image.", "types.imageSizeError": "The image must not exceed 5 MB.", "types.imageUrlError": "Enter a valid HTTP or HTTPS image URL.", "types.imageRequired": "Choose an image before saving, or turn off the image option.",
  ...inventoryEn,
  ...pricingEn,
} as const;
