export const en = {
  "language.en": "English", "language.ps": "Pashto", "language.dr": "Dari",
  "common.profile": "Profile", "common.logout": "Log out", "common.notifications": "Notifications",
  "dashboard.subtitle": "Overview of your store activity and performance.", "create.title": "Create product", "create.subtitle": "Add a new product to your catalog.", "create.back": "Back",
  "nav.platform": "Platform", "nav.dashboard": "Dashboard", "nav.products": "Products", "nav.allProducts": "All Products", "nav.categories": "Categories", "nav.brands": "Brands", "nav.units": "Units", "nav.inventory": "Inventory", "nav.stockOverview": "Stock Overview", "nav.stockTransactions": "Stock Transactions", "nav.lowStock": "Low Stock", "nav.orders": "Orders", "nav.allOrders": "All Orders", "nav.pendingOrders": "Pending Orders", "nav.completedOrders": "Completed Orders", "nav.cancelledOrders": "Cancelled Orders", "nav.customers": "Customers", "nav.allCustomers": "All Customers", "nav.customerTypes": "Customer Types", "nav.system": "System", "nav.generalTypes": "General Types", "nav.users": "Users", "nav.roles": "Roles & Permissions",
  "products.title": "Products", "products.subtitle": "Manage your store products", "products.updateSelected": "Update selected", "products.bulkCreate": "Bulk create", "products.search": "Search by name or barcode...", "products.product": "Product", "products.barcode": "Barcode", "products.category": "Category", "products.price": "Price", "products.stock": "Stock", "products.status": "Status", "products.active": "Active", "products.inactive": "Inactive", "products.empty": "No products found.", "products.loadError": "Products could not be loaded.",
  "form.name": "Name", "form.parent": "Parent", "form.save": "Save", "form.cancel": "Cancel", "form.description": "Description", "form.shortDescription": "Short description", "form.slug": "Slug", "form.minimum": "Minimum value", "form.maximum": "Maximum value", "form.brand": "Brand", "form.unit": "Unit", "form.none": "None", "form.search": "Search", "form.noMatch": "No matching option.",
  "bulk.title": "Bulk product creation", "bulk.subtitle": "Select multiple images and enter the information for each product.", "bulk.clear": "Clear all", "bulk.noProducts": "No products selected", "bulk.selectImages": "Select product images to generate the forms.", "bulk.ready": "ready", "bulk.submitTogether": "All products will be submitted together.", "bulk.create": "Create", "bulk.creating": "Creating products...", "bulk.productName": "Product name", "bulk.replaceImage": "Replace image", "bulk.activeProduct": "Active product", "bulk.activeHelp": "Product can be used in the system.", "bulk.featuredProduct": "Featured product", "bulk.featuredHelp": "Display this product as featured.",
  "uploader.drop": "Drop images here", "uploader.title": "Upload product images", "uploader.instructions": "Drag and drop images here, choose them from your device, or paste copied images.", "uploader.pasteBefore": "Click this area, then press", "uploader.pasteAfter": "to paste.", "uploader.formats": "JPG, PNG or WEBP. Maximum 5 MB per image.", "uploader.choose": "Choose images",
  "update.title": "Update product", "update.bulkTitle": "Bulk update products", "update.subtitle": "Update every product field and optionally replace its primary image. All changes are submitted together.", "update.close": "Close editor", "update.untitled": "Untitled", "update.replaceImage": "Replace image", "update.keepImage": "Leave empty to keep the current image.", "update.productNumber": "Product", "update.category": "Category", "update.barcode": "Barcode", "update.searchOption": "Search options...", "update.noMatch": "No matching option.", "update.activeHelp": "Product is available for use in the store.", "update.featuredHelp": "Highlight this product in featured sections.", "update.previous": "Previous", "update.next": "Next", "update.submit": "Update products", "update.submitting": "Updating products...", "update.success": "Products updated successfully.", "update.connectionError": "Cannot connect to the product API. Restart the backend and try again.", "update.endpointError": "The backend is running an older update endpoint. Restart it and try again.", "update.failed": "Product update failed.",
  "types.title": "General Types", "types.subtitle": "Manage your store General Types", "types.add": "Add Type", "types.create": "Create General Type", "types.edit": "Edit General Type", "types.group": "Group", "types.actions": "Actions",
} as const;
