import type { en } from "./en";
export const ps: Record<keyof typeof en, string> = {
  "language.en": "انګلیسي", "language.ps": "پښتو", "language.dr": "دري",
  "common.profile": "پروفایل", "common.logout": "وتل", "common.notifications": "خبرتیاوې",
  "dashboard.subtitle": "د خپل پلورنځي د فعالیت او پایلو لنډیز.", "create.title": "محصول جوړول", "create.subtitle": "خپل کتالوګ ته نوی محصول ورزیات کړئ.", "create.back": "شاته",
  "nav.platform": "پلېټفارم", "nav.dashboard": "ډشبورډ", "nav.products": "محصولات", "nav.allProducts": "ټول محصولات", "nav.categories": "کټګورۍ", "nav.brands": "برانډونه", "nav.units": "واحدونه", "nav.inventory": "زېرمتون", "nav.stockOverview": "د موجودۍ لنډیز", "nav.stockTransactions": "د موجودۍ راکړه ورکړه", "nav.lowStock": "کمه موجودي", "nav.orders": "سپارښتنې", "nav.allOrders": "ټولې سپارښتنې", "nav.pendingOrders": "پاتې سپارښتنې", "nav.completedOrders": "بشپړې سپارښتنې", "nav.cancelledOrders": "لغوه شوې سپارښتنې", "nav.customers": "پېرودونکي", "nav.allCustomers": "ټول پېرودونکي", "nav.customerTypes": "د پېرودونکو ډولونه", "nav.system": "سیسټم", "nav.generalTypes": "عمومي ډولونه", "nav.users": "کاروونکي", "nav.roles": "رولونه او اجازې",
  "products.title": "محصولات", "products.subtitle": "د پلورنځي محصولات اداره کړئ", "products.updateSelected": "ټاکل شوي نوي کړئ", "products.bulkCreate": "ډله‌ییز جوړول", "products.search": "د نوم یا بارکوډ له مخې لټون...", "products.product": "محصول", "products.barcode": "بارکوډ", "products.category": "کټګوري", "products.price": "بیه", "products.stock": "موجودي", "products.status": "حالت", "products.active": "فعال", "products.inactive": "غیرفعال", "products.empty": "هیڅ محصول ونه موندل شو.", "products.loadError": "محصولات پورته نه شول.",
  "form.name": "نوم", "form.parent": "اصلي", "form.save": "خوندي کول", "form.cancel": "لغوه کول", "form.description": "تشریح", "form.shortDescription": "لنډه تشریح", "form.slug": "سلګ", "form.minimum": "لږ تر لږه ارزښت", "form.maximum": "ډېر تر ډېره ارزښت", "form.brand": "برانډ", "form.unit": "واحد", "form.none": "هیڅ", "form.search": "لټون", "form.noMatch": "برابر انتخاب ونه موندل شو.",
  "bulk.title": "د محصولاتو ډله‌ییز جوړول", "bulk.subtitle": "څو انځورونه وټاکئ او د هر محصول معلومات ولیکئ.", "bulk.clear": "ټول پاکول", "bulk.noProducts": "هیڅ محصول نه دی ټاکل شوی", "bulk.selectImages": "د فورمو جوړولو لپاره د محصول انځورونه وټاکئ.", "bulk.ready": "چمتو", "bulk.submitTogether": "ټول محصولات به یوځای ولېږل شي.", "bulk.create": "جوړول", "bulk.creating": "محصولات جوړېږي...", "bulk.productName": "د محصول نوم", "bulk.replaceImage": "انځور بدلول", "bulk.activeProduct": "فعال محصول", "bulk.activeHelp": "محصول په سیسټم کې کارېدلی شي.", "bulk.featuredProduct": "ځانګړی محصول", "bulk.featuredHelp": "محصول په ځانګړو برخو کې ښکاره کړئ.",
  "uploader.drop": "انځورونه دلته پرېږدئ", "uploader.title": "د محصول انځورونه پورته کړئ", "uploader.instructions": "انځورونه دلته راکش کړئ، له وسیلې یې وټاکئ، یا کاپي شوي انځورونه ونښلوئ.", "uploader.pasteBefore": "په دې برخه کلیک وکړئ، بیا فشار ورکړئ", "uploader.pasteAfter": "د نښلولو لپاره.", "uploader.formats": "JPG، PNG یا WEBP. د هر انځور اعظمي اندازه ۵ MB ده.", "uploader.choose": "انځورونه ټاکل",
  "update.title": "محصول نوی کول", "update.bulkTitle": "د محصولاتو ډله‌ییز نوی کول", "update.subtitle": "د محصول ټول معلومات نوي کړئ او که وغواړئ اصلي انځور بدل کړئ. ټول بدلونونه یوځای لېږل کېږي.", "update.close": "سمونګر تړل", "update.untitled": "بې نومه", "update.replaceImage": "انځور بدلول", "update.keepImage": "د اوسني انځور ساتلو لپاره تش پرېږدئ.", "update.productNumber": "محصول", "update.category": "کټګوري", "update.barcode": "بارکوډ", "update.searchOption": "په انتخابونو کې لټون...", "update.noMatch": "برابر انتخاب ونه موندل شو.", "update.activeHelp": "محصول په پلورنځي کې د کارولو لپاره شته.", "update.featuredHelp": "محصول په ځانګړو برخو کې ښکاره کړئ.", "update.previous": "مخکینی", "update.next": "بل", "update.submit": "محصولات نوي کول", "update.submitting": "محصولات نوي کېږي...", "update.success": "محصولات په بریالیتوب نوي شول.", "update.connectionError": "د محصولاتو API سره اړیکه نشي نیول کېدای. شالید بیا چالان او بیا هڅه وکړئ.", "update.endpointError": "شالید د نوي کولو پخوانۍ لاره کاروي. بیا یې چالان او هڅه وکړئ.", "update.failed": "د محصول نوي کول ناکام شول.",
  "types.title": "عمومي ډولونه", "types.subtitle": "د پلورنځي عمومي ډولونه اداره کړئ", "types.add": "ډول زیاتول", "types.create": "عمومي ډول جوړول", "types.edit": "عمومي ډول سمول", "types.group": "ډله", "types.actions": "کړنې",
};
