import type { en } from "./en";
import { inventoryPs } from "@/features/inventory/i18n/inventory-translations";
import { pricingPs } from "@/features/products/i18n/pricing-translations";
import { tenancyPs } from "@/features/tenancy/i18n/tenant-translations";

export const ps: Record<keyof typeof en, string> = {
  "language.en": "انګلیسي", "language.ps": "پښتو", "language.dr": "دري",
  "common.continue": "ادامه", "common.working": "کار روان دی…", "common.searching": "لټون روان دی…", "common.checkingSession": "د ادارې ناسته کتل کېږي…",
  "access.required": "اجازه اړینه ده", "access.descriptionBefore": "ستاسو حساب دا اجازه نه لري:", "access.descriptionAfter": "د شرکت له مدیر څخه وغواړئ چې رول یا مستقیمه اجازه درکړي، بیا بېرته ننوځئ.", "access.allowedSection": "اجازه شوې برخې ته تلل",
  "notFound.error": "۴۰۴ تېروتنه", "notFound.title": "دا اداري پاڼه نشته", "notFound.description": "کېدای شي لینک زوړ وي، پاڼه لېږدول شوې وي، یا پته ناسمه لیکل شوې وي.", "notFound.back": "شاته", "notFound.dashboard": "ډشبورډ پرانیستل",
  "common.profile": "پروفایل", "common.logout": "وتل", "common.notifications": "خبرتیاوې", "common.loading": "پورته کېږي…",
  "auth.brand": "د پلورنځي اداره", "auth.protected": "خوندي اداره", "auth.heroTitle": "محصولات، پېرودونکي، سپارښتنې او تادیات په خوندي ډول اداره کړئ.", "auth.heroDescription": "لاسرسی د شرکت د رولونو او سپارل شویو اجازو له لارې کنټرلېږي. کارکوونکي یوازې ټاکل شوې برخې ویني.", "auth.environmentHelp": "له تولیدي خپرونې مخکې د چاپېریال د ننوتلو معلومات وکاروئ.", "auth.access": "د ادارې لاسرسی", "auth.welcome": "بیا ښه راغلاست", "auth.description": "د دې شرکت لپاره د مدیر ایمیل یا کارن نوم او پټنوم سره ننوځئ.", "auth.company": "د شرکت کاري چاپېریال", "auth.companyPlaceholder": "ستاسو-شرکت", "auth.companyHelp": "د خپلې ګډون‌پاڼې سره ورکړل شوی د شرکت سلګ وکاروئ.", "auth.identifier": "ایمیل یا کارن نوم", "auth.identifierPlaceholder": "admin@company.com", "auth.password": "پټنوم", "auth.showPassword": "پټنوم ښودل", "auth.hidePassword": "پټنوم پټول", "auth.signingIn": "ننوتل روان دي…", "auth.signIn": "په خوندي ډول ننوتل", "auth.failed": "ننوتل ناکام شول.", "nav.noModules": "دې حساب ته هېڅ برخه نه ده ټاکل شوې.",
  "dashboard.subtitle": "د خپل پلورنځي د فعالیت او پایلو لنډیز.", "create.title": "محصول جوړول", "create.subtitle": "خپل کتالوګ ته نوی محصول ورزیات کړئ.", "create.back": "شاته",
  "nav.platform": "پلېټفارم", "nav.dashboard": "ډشبورډ", "nav.products": "محصولات", "nav.allProducts": "ټول محصولات", "nav.categories": "کټګورۍ", "nav.brands": "برانډونه", "nav.units": "واحدونه", "nav.inventory": "زېرمتون", "nav.stockOverview": "د موجودۍ لنډیز", "nav.stockTransactions": "د موجودۍ راکړه ورکړه", "nav.lowStock": "کمه موجودي", "nav.orders": "سپارښتنې", "nav.allOrders": "ټولې سپارښتنې", "nav.pendingOrders": "پاتې سپارښتنې", "nav.completedOrders": "بشپړې سپارښتنې", "nav.cancelledOrders": "لغوه شوې سپارښتنې", "nav.customers": "پېرودونکي", "nav.allCustomers": "ټول پېرودونکي", "nav.customerTypes": "د پېرودونکو ډولونه", "nav.system": "سیسټم", "nav.generalTypes": "عمومي ډولونه", "nav.users": "کاروونکي", "nav.roles": "رولونه او اجازې",
  "products.title": "محصولات", "products.subtitle": "د پلورنځي محصولات اداره کړئ", "products.navigation": "د محصولاتو پاڼې", "products.updateSelected": "ټاکل شوي نوي کړئ", "products.bulkCreate": "ډله‌ییز جوړول", "products.search": "د نوم یا بارکوډ له مخې لټون...", "products.product": "محصول", "products.barcode": "بارکوډ", "products.category": "کټګوري", "products.price": "بیه", "products.stock": "موجودي", "products.status": "حالت", "products.active": "فعال", "products.inactive": "غیرفعال", "products.empty": "هیڅ محصول ونه موندل شو.", "products.loadError": "محصولات پورته نه شول.", "products.refreshing": "محصولات نوي کېږي...",
  "filters.title": "فلټرونه", "filters.description": "د کتالوګ معلوماتو، حالت، بیې او ترتیب له مخې د محصولاتو لړ لنډ کړئ.", "filters.all": "ټول", "filters.yes": "هو", "filters.no": "نه", "filters.featured": "ځانګړی", "filters.sort": "ترتیب", "filters.newest": "نوي لومړی", "filters.oldest": "زاړه لومړی", "filters.nameAsc": "نوم الف–ی", "filters.nameDesc": "نوم ی–الف", "filters.priceAsc": "بیه: له ټیټې تر لوړې", "filters.priceDesc": "بیه: له لوړې تر ټیټې", "filters.minPrice": "لږ تر لږه بیه", "filters.maxPrice": "ډېر تر ډېره بیه", "filters.clear": "فلټرونه پاکول", "filters.removeAll": "فلټرونه لرې کول", "filters.apply": "فلټرونه پلي کول", "filters.clearSearch": "لټون پاکول",
  "pagination.showing": "ښودل کېږي", "pagination.of": "له", "pagination.rows": "په پاڼه کې کتارونه", "pagination.previous": "مخکینۍ پاڼه", "pagination.next": "بله پاڼه", "pagination.page": "پاڼه",
  "form.name": "نوم", "form.parent": "اصلي", "form.save": "خوندي کول", "form.cancel": "لغوه کول", "form.description": "تشریح", "form.shortDescription": "لنډه تشریح", "form.slug": "سلګ", "form.minimum": "لږ تر لږه ارزښت", "form.maximum": "ډېر تر ډېره ارزښت", "form.brand": "برانډ", "form.unit": "واحد", "form.none": "هیڅ", "form.search": "لټون", "form.noMatch": "برابر انتخاب ونه موندل شو.",
  "bulk.title": "د محصولاتو ډله‌ییز جوړول", "bulk.subtitle": "څو انځورونه وټاکئ او د هر محصول معلومات ولیکئ.", "bulk.clear": "ټول پاکول", "bulk.noProducts": "هیڅ محصول نه دی ټاکل شوی", "bulk.selectImages": "د فورمو جوړولو لپاره د محصول انځورونه وټاکئ.", "bulk.ready": "چمتو", "bulk.submitTogether": "ټول محصولات به یوځای ولېږل شي.", "bulk.create": "جوړول", "bulk.creating": "محصولات جوړېږي...", "bulk.productName": "د محصول نوم", "bulk.replaceImage": "انځور بدلول", "bulk.activeProduct": "فعال محصول", "bulk.activeHelp": "محصول په سیسټم کې کارېدلی شي.", "bulk.featuredProduct": "ځانګړی محصول", "bulk.featuredHelp": "محصول په ځانګړو برخو کې ښکاره کړئ.",
  "uploader.drop": "انځورونه دلته پرېږدئ", "uploader.title": "د محصول انځورونه پورته کړئ", "uploader.instructions": "انځورونه دلته راکش کړئ، له وسیلې یې وټاکئ، یا کاپي شوي انځورونه ونښلوئ.", "uploader.pasteBefore": "په دې برخه کلیک وکړئ، بیا فشار ورکړئ", "uploader.pasteAfter": "د نښلولو لپاره.", "uploader.formats": "JPG، PNG، WEBP یا AVIF. د هر انځور اعظمي اندازه ۵ MB ده.", "uploader.choose": "انځورونه ټاکل",
  "update.title": "محصول نوی کول", "update.bulkTitle": "د محصولاتو ډله‌ییز نوی کول", "update.subtitle": "د محصول ټول معلومات نوي کړئ او که وغواړئ اصلي انځور بدل کړئ. ټول بدلونونه یوځای لېږل کېږي.", "update.close": "سمونګر تړل", "update.untitled": "بې نومه", "update.replaceImage": "انځور بدلول", "update.keepImage": "د اوسني انځور ساتلو لپاره تش پرېږدئ.", "update.galleryImages": "د ګالري انځورونه", "update.galleryHelp": "د دې ټاکل شوي محصول لپاره نور انځورونه زیات کړئ.", "update.addGalleryImages": "د ګالري انځورونه زیاتول", "update.removeGalleryImage": "د ګالري انځور لرې کول", "update.galleryLimit": "یو محصول تر ۱۰ ډېر انځورونه نشي لرلای.", "update.productNumber": "محصول", "update.category": "کټګوري", "update.barcode": "بارکوډ", "update.searchOption": "په انتخابونو کې لټون...", "update.noMatch": "برابر انتخاب ونه موندل شو.", "update.activeHelp": "محصول په پلورنځي کې د کارولو لپاره شته.", "update.featuredHelp": "محصول په ځانګړو برخو کې ښکاره کړئ.", "update.previous": "مخکینی", "update.next": "بل", "update.submit": "محصولات نوي کول", "update.submitting": "محصولات نوي کېږي...", "update.success": "محصولات په بریالیتوب نوي شول.", "update.connectionError": "د محصولاتو API سره اړیکه نشي نیول کېدای. شالید بیا چالان او بیا هڅه وکړئ.", "update.endpointError": "شالید د نوي کولو پخوانۍ لاره کاروي. بیا یې چالان او هڅه وکړئ.", "update.failed": "د محصول نوي کول ناکام شول.",
  "types.title": "عمومي ډولونه", "types.subtitle": "د بیا کارېدونکو کټګوریو، برانډونو، واحدونو او پېرودونکو ډولونه اداره کړئ.", "types.add": "ډول زیاتول", "types.create": "عمومي ډول جوړول", "types.edit": "عمومي ډول سمول", "types.group": "ډله", "types.actions": "کړنې", "types.all": "ټول ډولونه", "types.category": "کټګورۍ", "types.brand": "برانډونه", "types.unit": "واحدونه", "types.customerType": "د پېرودونکو ډولونه", "types.expenseCategory": "د لګښت کټګورۍ", "types.unknownGroup": "نور", "types.search": "ډولونه ولټوئ...", "types.refresh": "ډولونه نوي کول", "types.loading": "ډولونه پورته کېږي...", "types.loadError": "ډولونه پورته نه شول.", "types.retry": "بیا هڅه", "types.empty": "هیڅ ډول ونه موندل شو", "types.emptyHelp": "فلټرونه بدل کړئ یا نوی ډول زیات کړئ.", "types.noParent": "اصلي نه لري (لوړه کچه)", "types.saving": "خوندي کېږي...", "types.created": "ډول په بریالیتوب جوړ شو.", "types.updated": "ډول په بریالیتوب نوی شو.", "types.saveError": "ډول خوندي نه شو.", "types.delete": "ړنګول", "types.deleting": "ډول ړنګېږي...", "types.deleted": "ډول په بریالیتوب ړنګ شو.", "types.deleteError": "دا ډول نشي ړنګېدای. لومړی یې فرعي یا تړلي معلومات لرې کړئ.", "types.deleteTitle": "دا ډول ړنګ کړئ؟", "types.deleteDescription": "دا کار بېرته نه راګرځي. د فرعي یا تړلو معلوماتو لرونکي ډولونه نشي ړنګېدای.",
  "update.savedImage": "خوندي شوی", "update.newImage": "نوی",
  "products.deleteSelected": "ټاکل شوي ړنګول", "products.deleteTitle": "ټاکل شوي محصولات ړنګ کړئ؟", "products.deleteDescription": "ټاکل شوي محصولات به له کتالوګ څخه لرې شي. دا کار د ادارې له برخې بېرته نه راګرځي.", "products.confirmDelete": "محصولات ړنګول", "products.deleting": "محصولات ړنګېږي...", "products.deleteSuccess": "محصولات په بریالیتوب ړنګ شول.", "products.deleteError": "ټاکل شوي محصولات ړنګ نه شول.",
  "details.subtitle": "د محصول بشپړ معلومات، انځورونه، زېرمه او بیې.", "details.back": "محصولاتو ته ستنېدل", "details.open": "د محصول جزئیات کتل", "details.notFound": "محصول ونه موندل شو", "details.notFoundHelp": "کېدای شي دا محصول ړنګ شوی یا د لاسرسي وړ نه وي.", "details.featured": "ځانګړی", "details.noDescription": "د دې محصول لپاره تشریح نه ده لیکل شوې.", "details.views": "کتنې", "details.created": "جوړ شوی", "details.updated": "وروستی نوی کول", "details.inventory": "زېرمه", "details.totalStock": "ټوله زېرمه", "details.availableStock": "شته زېرمه", "details.reservedStock": "ساتل شوې زېرمه", "details.minimumStock": "لږ تر لږه زېرمه", "details.expiry": "د پای نېټه", "details.pricing": "بیې", "details.noPrices": "د پېرودونکو لپاره بیې نه دي ټاکل شوې.",
  "types.image": "انځور", "types.imageUrl": "د انځور پته", "types.imageUrlHelp": "د انځور لپاره عامه HTTP یا HTTPS پته ولیکئ.", "types.useImage": "انځور کارول", "types.useImageHelp": "اختیاري دی. یوازې هغه وخت یې فعال کړئ چې دا ډول انځور ته اړتیا ولري.", "types.imageSource": "د انځور سرچینه", "types.uploadImage": "انځور پورته کول", "types.onlineUrl": "انلاین پته", "types.chooseImage": "له وسیلې څخه انځور وټاکئ", "types.imageFileHelp": "JPG، PNG، WEBP یا AVIF، تر ۵ MB پورې.", "types.imagePreview": "د ډول انځور مخکتنه", "types.removeImage": "انځور لرې کول", "types.imageFormatError": "یو معتبر JPG، PNG، WEBP یا AVIF انځور وټاکئ.", "types.imageSizeError": "انځور باید له ۵ MB څخه لوی نه وي.", "types.imageUrlError": "یوه معتبره HTTP یا HTTPS پته ولیکئ.", "types.imageRequired": "له خوندي کولو مخکې انځور وټاکئ یا د انځور اختیار بند کړئ.",
  "nav.workspace": "کاري چاپېریال", "nav.commerce": "سوداګري", "nav.operations": "عملیات", "nav.administration": "اداره", "nav.reports": "راپورونه", "nav.reviews": "کتنې", "nav.overview": "لنډیز", "nav.purchases": "پېرودونه", "nav.manualSales": "لاسي پلور", "nav.staffPayroll": "کارکوونکي او معاش", "nav.expenses": "لګښتونه", "nav.company": "د شرکت پروفایل", "nav.storefront": "پلورنځی", "nav.trash": "کثافات", "nav.tenants": "کرایه‌وال شرکتونه",
  ...inventoryPs,
  ...pricingPs,
  ...tenancyPs,
};
