export interface PagedResult<T> { items: T[]; page: number; pageSize: number; totalCount: number; totalPages: number; hasPreviousPage: boolean; hasNextPage: boolean }
export type PaymentStatus = "Unpaid" | "Partial" | "Paid";
export interface OperationSummary { purchasesThisMonth: number; salesThisMonth: number; expensesThisMonth: number; salariesThisMonth: number; lowStockProducts: number; currencyCode: string }
export interface OperationPolicy { maximumPurchaseLines: number; maximumManualSaleLines: number; canOverrideLineLimits: boolean; generalSalesDiscountPercent: number; maximumCustomerDebt: number; defaultDebtDueDays: number; allowNegativeStockSales: boolean }
export interface OperationProductUnit { unitId: number; unitName: string; conversionFactor: number; barcode: string | null; defaultPrice: number | null; availableQuantity: number; isBase: boolean; isDefault: boolean }
export interface OperationProduct { id: number; name: string; strength: string | null; genericName: string | null; formula: string | null; barcode: string | null; availableQuantity: number; defaultPrice: number | null; minimumValue: number | null; maximumValue: number | null; usesDisplayStock: boolean; baseUnitId: number | null; baseUnitName: string | null; currentUnitCost: number | null; units: OperationProductUnit[] }
export interface QuickCreateProduct { name: string; barcode: string | null; strength: string | null; genericName: string | null; formula: string | null; categoryId: number; unitId: number; defaultSalePrice: number | null }
export interface OperationCustomer { id: number; name: string; phone: string; whatsAppUrl: string | null; email: string | null; customerTypeName: string | null; accountCredit: number; outstandingDebt: number; creditLimit: number; hasOverdueDebt: boolean }
export interface Supplier { id: number; name: string; contactPerson: string | null; phone: string | null; email: string | null; address: string | null; taxNumber: string | null; isActive: boolean; outstandingBalance: number }
export interface SupplierLedgerEntry { date: string; type: string; reference: string; description: string; debit: number; credit: number; balance: number; sourceId: number }
export interface SupplierLedger { supplierId: number; supplierName: string; currencyCode: string; totalPurchases: number; totalPayments: number; closingBalance: number; entries: SupplierLedgerEntry[] }
export interface PartySettlementDocument { id: number; documentNumber: string; documentDate: string; currencyCode: string; total: number; paidAmount: number; remainingAmount: number; paymentStatus: PaymentStatus }
export interface Purchase { id: number; purchaseNumber: string; referenceNumber: string | null; purchaseDate: string; supplierName: string | null; itemCount: number; total: number; paidAmount: number; remainingAmount: number; paymentStatus: PaymentStatus; status: "Draft" | "Received" | "Cancelled"; createdAt: string }
export interface PurchaseItemDetails { id: number; productId: number; productName: string; strength: string | null; barcode: string | null; quantity: number; unitCost: number; enteredQuantity: number; selectedUnitId: number | null; selectedUnitName: string | null; unitConversionFactor: number; enteredUnitCost: number; lineTotal: number; bonusQuantity: number; discountPercent: number; lotNumber: string | null; expireDate: string | null }
export interface PurchaseDetails { id: number; purchaseNumber: string; referenceNumber: string | null; purchaseDate: string; supplierId: number | null; supplierName: string | null; status: "Draft" | "Received" | "Cancelled"; paymentStatus: PaymentStatus; subtotal: number; discount: number; discountPercent: number; secondaryDiscountPercent: number; tax: number; otherCost: number; total: number; paidAmount: number; remainingAmount: number; currencyCode: string; notes: string | null; createdAt: string; items: PurchaseItemDetails[] }
export interface ManualSale { id: number; saleNumber: string; referenceNumber: string | null; saleDate: string; customerId: number | null; customerName: string; customerPhone: string | null; notes: string | null; whatsAppUrl: string | null; itemCount: number; total: number; returnedAmount: number; paidAmount: number; remainingAmount: number; paymentStatus: PaymentStatus; costOfGoods: number; grossProfit: number; profitMargin: number; createdAt: string }
export interface ManualSaleItemDetails { id: number; productId: number; productName: string; strength: string | null; barcode: string | null; quantity: number; unitPrice: number; unitCost: number; enteredQuantity: number; selectedUnitId: number | null; selectedUnitName: string | null; unitConversionFactor: number; enteredUnitPrice: number; lineTotal: number; bonusQuantity: number; discountPercent: number }
export interface ManualSaleDetails { id: number; saleNumber: string; referenceNumber: string | null; saleDate: string; customerId: number | null; customerName: string; customerPhone: string | null; paymentStatus: PaymentStatus; subtotal: number; discount: number; discountPercent: number; secondaryDiscountPercent: number; tax: number; total: number; returnedAmount: number; paidAmount: number; remainingAmount: number; currencyCode: string; notes: string | null; debtDueDate: string | null; customerCreditApplied: number; customerCreditCreated: number; createdAt: string; items: ManualSaleItemDetails[] }
export type SalesReturnSettlementMode = "Refund" | "CustomerCredit";
export interface SalesReturnItem { id: number; saleItemId: number; productId: number; productName: string; quantity: number; unitName: string | null; lineTotal: number; restocked: boolean }
export interface SalesReturn { id: number; returnNumber: string; saleId: number; saleNumber: string; returnDate: string; settlementMode: SalesReturnSettlementMode; total: number; taxAmount: number; debtReduction: number; refundAmount: number; creditAmount: number; refundMethod: string; currencyCode: string; reason: string; notes: string | null; createdAt: string; items: SalesReturnItem[] }
export interface ManualSaleLotMovement { id: number; productId: number; productName: string; inventoryLotId: number | null; lotNumber: string | null; warehouseId: number; warehouseName: string; expiresAt: string | null; quantity: number; createdAt: string }
export interface Staff { id: number; employeeNumber: string; fullName: string; phone: string | null; email: string | null; position: string | null; department: string | null; hireDate: string; baseSalary: number; isActive: boolean; address: string | null; notes: string | null; isSystemUser: boolean }
export interface SalaryPayment { id: number; staffId: number; staffName: string; periodYear: number; periodMonth: number; baseSalary: number; bonus: number; deduction: number; netAmount: number; paidAmount: number; remainingAmount: number; paymentStatus: PaymentStatus; paidDate: string; paymentMethod: string; referenceNumber: string | null; createdAt: string }
export interface ExpenseCategory { id: number; name: string; description: string | null; isActive: boolean }
export interface Expense { id: number; expenseDate: string; categoryId: number; categoryName: string; amount: number; vendor: string | null; paymentMethod: string; referenceNumber: string | null; description: string; createdAt: string }
export type JournalVoucherType = "ManualAdjustment" | "OpeningBalance" | "FundsTransfer" | "OwnerEquity" | "Purchase" | "PurchasePayment" | "ManualSale" | "SaleReceipt" | "SalesReturn" | "OnlineSale" | "OnlineReceipt" | "Expense" | "PayrollAccrual" | "PayrollPayment" | "Reversal";
export type JournalVoucherStatus = "Posted" | "Reversed";
export interface JournalVoucherLine { id: number; accountCode: string; accountName: string; description: string | null; debit: number; credit: number }
export interface JournalVoucher { id: number; voucherNumber: string; voucherDate: string; currencyCode: string; voucherType: JournalVoucherType; status: JournalVoucherStatus; isSystemGenerated: boolean; referenceNumber: string | null; sourceType: string | null; sourceId: number | null; sourceNumber: string | null; counterpartyType: string | null; counterpartyId: number | null; counterpartyName: string | null; memo: string; totalDebit: number; totalCredit: number; operatorName: string | null; postedAt: string; reversedAt: string | null; reversalReason: string | null; reversalOfVoucherId: number | null; reversalVoucherId: number | null; createdAt: string; lines: JournalVoucherLine[] }
export interface JournalAccountBalance { accountCode: string; accountName: string; currencyCode: string; totalDebit: number; totalCredit: number; balance: number; entryCount: number }
export interface JournalAccountLedgerEntry { voucherId: number; voucherNumber: string; voucherDate: string; voucherType: JournalVoucherType; memo: string; referenceNumber: string | null; counterpartyName: string | null; debit: number; credit: number; balance: number; status: JournalVoucherStatus; isReversal: boolean }
export interface JournalAccountLedger { accountCode: string; accountName: string; currencyCode: string; startDate: string; endDate: string; openingBalance: number; periodDebit: number; periodCredit: number; closingBalance: number; entries: JournalAccountLedgerEntry[] }
export interface JournalVoucherSummary { totalVouchers: number; systemGeneratedVouchers: number; manualVouchers: number; reversedVouchers: number; totalPostedDebits: number; currencyCode: string; lastPostingDate: string | null }
export interface CreateJournalVoucher { voucherDate: string; currencyCode: string; voucherType: Extract<JournalVoucherType, "ManualAdjustment" | "OpeningBalance" | "FundsTransfer" | "OwnerEquity">; memo: string; referenceNumber: string | null; lines: { accountCode: string; accountName: string; description: string | null; debit: number; credit: number }[] }
export interface DocumentPayment { id: number; amount: number; paymentDate: string; paymentMethod: string; referenceNumber: string | null; notes: string | null; createdAt: string }
export interface RecordDocumentPayment { amount: number; paymentDate: string; paymentMethod: string; referenceNumber: string | null; notes: string | null }
export interface DocumentItem { productId: number; unitId: number | null; unitName: string | null; conversionFactor: number; quantity: number; amount: number; bonusQuantity: number; discountPercent: number; lotNumber?: string; expireDate?: string | null; product?: OperationProduct | null }
