export type PaymentStatus = "Unpaid" | "Partial" | "Paid";
export interface OperationSummary { purchasesThisMonth: number; salesThisMonth: number; expensesThisMonth: number; salariesThisMonth: number; lowStockProducts: number }
export interface OperationPolicy { maximumPurchaseLines: number; maximumManualSaleLines: number; canOverrideLineLimits: boolean }
export interface OperationProductUnit { unitId: number; unitName: string; conversionFactor: number; barcode: string | null; defaultPrice: number | null; availableQuantity: number; isBase: boolean; isDefault: boolean }
export interface OperationProduct { id: number; name: string; strength: string | null; barcode: string | null; availableQuantity: number; defaultPrice: number | null; minimumValue: number | null; maximumValue: number | null; usesDisplayStock: boolean; baseUnitId: number | null; baseUnitName: string | null; units: OperationProductUnit[] }
export interface OperationCustomer { id: number; name: string; phone: string; email: string | null; customerTypeName: string | null }
export interface Supplier { id: number; name: string; contactPerson: string | null; phone: string | null; email: string | null; address: string | null; taxNumber: string | null; isActive: boolean }
export interface Purchase { id: number; purchaseNumber: string; referenceNumber: string | null; purchaseDate: string; supplierName: string | null; itemCount: number; total: number; paidAmount: number; remainingAmount: number; paymentStatus: PaymentStatus; status: "Draft" | "Received" | "Cancelled"; createdAt: string }
export interface PurchaseItemDetails { id: number; productId: number; productName: string; strength: string | null; barcode: string | null; quantity: number; unitCost: number; enteredQuantity: number; selectedUnitId: number | null; selectedUnitName: string | null; unitConversionFactor: number; enteredUnitCost: number; lineTotal: number; lotNumber: string | null; expireDate: string | null }
export interface PurchaseDetails { id: number; purchaseNumber: string; referenceNumber: string | null; purchaseDate: string; supplierId: number | null; supplierName: string | null; status: "Draft" | "Received" | "Cancelled"; paymentStatus: PaymentStatus; subtotal: number; discount: number; tax: number; otherCost: number; total: number; paidAmount: number; remainingAmount: number; currencyCode: string; notes: string | null; createdAt: string; items: PurchaseItemDetails[] }
export interface ManualSale { id: number; saleNumber: string; referenceNumber: string | null; saleDate: string; customerName: string; itemCount: number; total: number; paidAmount: number; remainingAmount: number; paymentStatus: PaymentStatus; createdAt: string }
export interface ManualSaleLotMovement { id: number; productId: number; productName: string; inventoryLotId: number | null; lotNumber: string | null; warehouseId: number; warehouseName: string; expiresAt: string | null; quantity: number; createdAt: string }
export interface Staff { id: number; employeeNumber: string; fullName: string; phone: string | null; email: string | null; position: string | null; department: string | null; hireDate: string; baseSalary: number; isActive: boolean; address: string | null; notes: string | null }
export interface SalaryPayment { id: number; staffId: number; staffName: string; periodYear: number; periodMonth: number; baseSalary: number; bonus: number; deduction: number; netAmount: number; paidAmount: number; remainingAmount: number; paymentStatus: PaymentStatus; paidDate: string; paymentMethod: string; referenceNumber: string | null; createdAt: string }
export interface ExpenseCategory { id: number; name: string; description: string | null; isActive: boolean }
export interface Expense { id: number; expenseDate: string; categoryId: number; categoryName: string; amount: number; vendor: string | null; paymentMethod: string; referenceNumber: string | null; description: string; createdAt: string }
export interface DocumentPayment { id: number; amount: number; paymentDate: string; paymentMethod: string; referenceNumber: string | null; notes: string | null; createdAt: string }
export interface DocumentItem { productId: number; unitId: number | null; unitName: string | null; conversionFactor: number; quantity: number; amount: number; lotNumber?: string; expireDate?: string | null; product?: OperationProduct | null }
