export const pricingEn = {
    "pricing.manage": "Manage prices", "pricing.title": "Product pricing", "pricing.description": "Set one price tier for each customer type and optionally schedule a sale.", "pricing.addTier": "Add price tier", "pricing.tier": "Price tier", "pricing.customerType": "Customer type", "pricing.regularPrice": "Regular price", "pricing.salePrice": "Sale price", "pricing.saleOptional": "Optional discount price", "pricing.startDate": "Sale starts", "pricing.endDate": "Sale ends", "pricing.removeTier": "Remove price tier", "pricing.discount": "{count}% off", "pricing.noTiers": "No prices configured", "pricing.noTiersHelp": "Add the first price tier to make this product purchasable.", "pricing.noCustomerTypes": "Create a customer type before adding prices.", "pricing.customerTypesHelp": "Customer types are managed under General Types.", "pricing.openCustomerTypes": "Manage customer types", "pricing.save": "Save prices", "pricing.saving": "Saving prices...", "pricing.success": "Product prices updated successfully.", "pricing.error": "Product prices could not be updated.", "pricing.invalidSale": "Sale price must be lower than the regular price.", "pricing.invalidDates": "Sale end date cannot be before its start date.", "pricing.duplicateType": "Each customer type can only have one price tier.", "pricing.regular": "Regular", "pricing.sale": "Sale", "pricing.schedule": "Schedule", "pricing.always": "No date limit", "pricing.active": "Active sale", "pricing.upcoming": "Upcoming", "pricing.ended": "Ended",
} as const;

export const pricingDr: Record<keyof typeof pricingEn, string> = {
    "pricing.manage": "مدیریت قیمت‌ها", "pricing.title": "قیمت‌گذاری محصول", "pricing.description": "برای هر نوع مشتری یک سطح قیمت تعیین و در صورت نیاز تخفیف را زمان‌بندی کنید.", "pricing.addTier": "افزودن سطح قیمت", "pricing.tier": "سطح قیمت", "pricing.customerType": "نوع مشتری", "pricing.regularPrice": "قیمت اصلی", "pricing.salePrice": "قیمت تخفیفی", "pricing.saleOptional": "قیمت تخفیفی اختیاری", "pricing.startDate": "شروع تخفیف", "pricing.endDate": "پایان تخفیف", "pricing.removeTier": "حذف سطح قیمت", "pricing.discount": "{count}٪ تخفیف", "pricing.noTiers": "قیمتی تنظیم نشده", "pricing.noTiersHelp": "برای قابل خرید شدن محصول، نخستین سطح قیمت را اضافه کنید.", "pricing.noCustomerTypes": "پیش از افزودن قیمت، یک نوع مشتری ایجاد کنید.", "pricing.customerTypesHelp": "انواع مشتری در بخش انواع عمومی مدیریت می‌شوند.", "pricing.openCustomerTypes": "مدیریت انواع مشتری", "pricing.save": "ذخیره قیمت‌ها", "pricing.saving": "در حال ذخیره قیمت‌ها...", "pricing.success": "قیمت‌های محصول با موفقیت به‌روز شد.", "pricing.error": "قیمت‌های محصول به‌روز نشد.", "pricing.invalidSale": "قیمت تخفیفی باید کمتر از قیمت اصلی باشد.", "pricing.invalidDates": "تاریخ پایان تخفیف نمی‌تواند پیش از شروع باشد.", "pricing.duplicateType": "هر نوع مشتری فقط می‌تواند یک سطح قیمت داشته باشد.", "pricing.regular": "اصلی", "pricing.sale": "تخفیف", "pricing.schedule": "زمان‌بندی", "pricing.always": "بدون محدودیت زمانی", "pricing.active": "تخفیف فعال", "pricing.upcoming": "آینده", "pricing.ended": "پایان‌یافته",
};

export const pricingPs: Record<keyof typeof pricingEn, string> = {
    "pricing.manage": "بیې اداره کړئ", "pricing.title": "د محصول بیې", "pricing.description": "د هر پېرودونکي ډول لپاره یوه بیه وټاکئ او تخفیف په اختیاري ډول مهالویش کړئ.", "pricing.addTier": "د بیې کچه زیاتول", "pricing.tier": "د بیې کچه", "pricing.customerType": "د پېرودونکي ډول", "pricing.regularPrice": "اصلي بیه", "pricing.salePrice": "تخفیفي بیه", "pricing.saleOptional": "اختیاري تخفیفي بیه", "pricing.startDate": "د تخفیف پیل", "pricing.endDate": "د تخفیف پای", "pricing.removeTier": "د بیې کچه لرې کول", "pricing.discount": "{count}٪ تخفیف", "pricing.noTiers": "بیې نه دي ټاکل شوې", "pricing.noTiersHelp": "د محصول د پېرلو لپاره لومړۍ بیه زیاته کړئ.", "pricing.noCustomerTypes": "د بیې له زیاتولو مخکې د پېرودونکي ډول جوړ کړئ.", "pricing.customerTypesHelp": "د پېرودونکو ډولونه د عمومي ډولونو په برخه کې اداره کېږي.", "pricing.openCustomerTypes": "د پېرودونکو ډولونه اداره کړئ", "pricing.save": "بیې خوندي کړئ", "pricing.saving": "بیې خوندي کېږي...", "pricing.success": "د محصول بیې په بریالیتوب نوې شوې.", "pricing.error": "د محصول بیې نوې نه شوې.", "pricing.invalidSale": "تخفیفي بیه باید له اصلي بیې کمه وي.", "pricing.invalidDates": "د تخفیف د پای نېټه له پیل مخکې نه شي کېدای.", "pricing.duplicateType": "د پېرودونکي هر ډول یوازې یوه بیه لرلی شي.", "pricing.regular": "اصلي", "pricing.sale": "تخفیف", "pricing.schedule": "مهالویش", "pricing.always": "د نېټې محدودیت نشته", "pricing.active": "فعال تخفیف", "pricing.upcoming": "راتلونکی", "pricing.ended": "پای ته رسېدلی",
};
