export const inventoryEn = {
    "inventory.title": "Inventory", "inventory.subtitle": "Monitor stock health, record movements, and keep every product ready to sell.", "inventory.refresh": "Refresh", "inventory.overview": "Stock overview", "inventory.transactions": "Transactions",
    "inventory.totalProducts": "Tracked products", "inventory.activeCount": "{count} active products", "inventory.availableUnits": "Available units", "inventory.onHandCount": "{count} total on hand", "inventory.reservedUnits": "Reserved units", "inventory.reservedHelp": "Committed to active orders", "inventory.lowStock": "Low stock", "inventory.expiringCount": "{count} expiring soon", "inventory.outOfStock": "Out of stock", "inventory.needsAttention": "Requires immediate attention",
    "inventory.stockCatalog": "Stock catalog", "inventory.stockCatalogHelp": "Prioritized by stock risk so products needing action appear first.", "inventory.search": "Search product or barcode...", "inventory.allStock": "All stock", "inventory.healthy": "Healthy", "inventory.allCategories": "All categories", "inventory.sortRecent": "Recently updated", "inventory.sortAvailable": "Available quantity", "inventory.sortOnHand": "On-hand quantity", "inventory.sortExpiry": "Expiry date", "inventory.sortName": "Product name", "inventory.stockStatus": "Stock status",
    "inventory.onHand": "On hand", "inventory.reserved": "Reserved", "inventory.available": "Available", "inventory.reorderPoint": "Reorder point", "inventory.expiryDate": "Expiry", "inventory.noBarcode": "No barcode", "inventory.loadError": "Inventory could not be loaded.", "inventory.empty": "No products match these inventory filters.", "inventory.adjustStock": "Adjust stock", "inventory.refreshing": "Refreshing inventory...", "inventory.expiringSoon": "Expiring soon",
    "inventory.adjustTitle": "Record stock movement", "inventory.adjustDescription": "Choose why stock is changing. The movement will be saved in the audit ledger.", "inventory.movementType": "Movement type", "inventory.quantity": "Quantity", "inventory.currentStock": "Current", "inventory.change": "Change", "inventory.newStock": "New total", "inventory.reservedGuard": "This removal would reduce stock below the quantity reserved for orders.", "inventory.note": "Internal note", "inventory.notePlaceholder": "Add a supplier reference, reason, or useful context...", "inventory.saving": "Saving...", "inventory.confirmAdjustment": "Record movement", "inventory.adjustSuccess": "Stock movement recorded successfully.", "inventory.adjustError": "Stock could not be adjusted.",
    "inventory.action.purchase": "Stock received", "inventory.action.purchaseHelp": "Add inventory received from a supplier.", "inventory.action.return": "Customer return", "inventory.action.returnHelp": "Return sellable items to available stock.", "inventory.action.addCorrection": "Positive correction", "inventory.action.addCorrectionHelp": "Increase stock after a physical count.", "inventory.action.removeCorrection": "Negative correction", "inventory.action.removeCorrectionHelp": "Reduce stock after a physical count.", "inventory.action.damaged": "Damaged stock", "inventory.action.damagedHelp": "Remove items that cannot be sold.", "inventory.action.expired": "Expired stock", "inventory.action.expiredHelp": "Remove items that passed their expiry date.",
    "inventory.settingsTitle": "Stock settings", "inventory.settingsDescription": "Set the alert threshold and optional expiry date for this product.", "inventory.reorderHelp": "The product becomes low stock when available units reach this value.", "inventory.expiryHelp": "Leave empty when this product does not expire.", "inventory.settingsSuccess": "Stock settings updated successfully.", "inventory.settingsError": "Stock settings could not be updated.",
    "inventory.ledgerTitle": "Stock movement ledger", "inventory.ledgerHelp": "A permanent, searchable history of receipts, sales, reservations, and corrections.", "inventory.searchTransactions": "Search product or barcode...", "inventory.allMovements": "All movement types", "inventory.fromDate": "From date", "inventory.toDate": "To date", "inventory.date": "Date", "inventory.beforeAfter": "Before → after", "inventory.noNote": "No note", "inventory.noTransactions": "No stock movements match these filters.", "inventory.transactionsError": "Stock movements could not be loaded.",
    "inventory.transaction.purchase": "Stock received", "inventory.transaction.sale": "Sale", "inventory.transaction.return": "Customer return", "inventory.transaction.adjustment": "Stock correction", "inventory.transaction.damaged": "Damaged", "inventory.transaction.expired": "Expired", "inventory.transaction.transfer": "Transfer", "inventory.transaction.reservation": "Reserved", "inventory.transaction.release": "Reservation released",
} as const;

export const inventoryDr: Record<keyof typeof inventoryEn, string> = {
    "inventory.title": "موجودی", "inventory.subtitle": "سلامت موجودی را بررسی، گردش‌ها را ثبت و محصولات را آماده فروش نگه دارید.", "inventory.refresh": "تازه‌سازی", "inventory.overview": "نمای کلی موجودی", "inventory.transactions": "تراکنش‌ها",
    "inventory.totalProducts": "محصولات تحت مدیریت", "inventory.activeCount": "{count} محصول فعال", "inventory.availableUnits": "واحدهای قابل دسترس", "inventory.onHandCount": "مجموع {count} واحد موجود", "inventory.reservedUnits": "واحدهای رزرو", "inventory.reservedHelp": "اختصاص‌یافته به سفارش‌های فعال", "inventory.lowStock": "موجودی کم", "inventory.expiringCount": "{count} مورد نزدیک به انقضا", "inventory.outOfStock": "ناموجود", "inventory.needsAttention": "نیازمند رسیدگی فوری",
    "inventory.stockCatalog": "فهرست موجودی", "inventory.stockCatalogHelp": "محصولات پُرخطر در اولویت نمایش داده می‌شوند.", "inventory.search": "جستجوی محصول یا بارکد...", "inventory.allStock": "همه موجودی", "inventory.healthy": "مناسب", "inventory.allCategories": "همه دسته‌بندی‌ها", "inventory.sortRecent": "آخرین به‌روزرسانی", "inventory.sortAvailable": "مقدار قابل دسترس", "inventory.sortOnHand": "مقدار موجود", "inventory.sortExpiry": "تاریخ انقضا", "inventory.sortName": "نام محصول", "inventory.stockStatus": "وضعیت موجودی",
    "inventory.onHand": "موجود", "inventory.reserved": "رزرو", "inventory.available": "قابل دسترس", "inventory.reorderPoint": "حد سفارش مجدد", "inventory.expiryDate": "انقضا", "inventory.noBarcode": "بدون بارکد", "inventory.loadError": "موجودی بارگذاری نشد.", "inventory.empty": "محصولی با این فیلترها یافت نشد.", "inventory.adjustStock": "تنظیم موجودی", "inventory.refreshing": "موجودی تازه‌سازی می‌شود...", "inventory.expiringSoon": "نزدیک به انقضا",
    "inventory.adjustTitle": "ثبت گردش موجودی", "inventory.adjustDescription": "دلیل تغییر موجودی را انتخاب کنید؛ این گردش در سابقه ثبت می‌شود.", "inventory.movementType": "نوع گردش", "inventory.quantity": "تعداد", "inventory.currentStock": "موجودی فعلی", "inventory.change": "تغییر", "inventory.newStock": "مجموع جدید", "inventory.reservedGuard": "این برداشت، موجودی را کمتر از مقدار رزروشده سفارش‌ها می‌سازد.", "inventory.note": "یادداشت داخلی", "inventory.notePlaceholder": "مرجع تأمین‌کننده، دلیل یا توضیح مفید را بنویسید...", "inventory.saving": "در حال ذخیره...", "inventory.confirmAdjustment": "ثبت گردش", "inventory.adjustSuccess": "گردش موجودی با موفقیت ثبت شد.", "inventory.adjustError": "تنظیم موجودی انجام نشد.",
    "inventory.action.purchase": "دریافت موجودی", "inventory.action.purchaseHelp": "موجودی دریافت‌شده از تأمین‌کننده را اضافه کنید.", "inventory.action.return": "برگشت مشتری", "inventory.action.returnHelp": "کالای قابل فروش را به موجودی برگردانید.", "inventory.action.addCorrection": "اصلاح افزایشی", "inventory.action.addCorrectionHelp": "پس از شمارش فزیکی، موجودی را افزایش دهید.", "inventory.action.removeCorrection": "اصلاح کاهشی", "inventory.action.removeCorrectionHelp": "پس از شمارش فزیکی، موجودی را کاهش دهید.", "inventory.action.damaged": "کالای آسیب‌دیده", "inventory.action.damagedHelp": "کالای غیرقابل فروش را کم کنید.", "inventory.action.expired": "کالای منقضی", "inventory.action.expiredHelp": "کالای گذشته از تاریخ را کم کنید.",
    "inventory.settingsTitle": "تنظیمات موجودی", "inventory.settingsDescription": "حد هشدار و تاریخ انقضای اختیاری این محصول را تعیین کنید.", "inventory.reorderHelp": "وقتی موجودی قابل دسترس به این مقدار برسد، محصول کم‌موجود نشان داده می‌شود.", "inventory.expiryHelp": "اگر محصول تاریخ انقضا ندارد، خالی بگذارید.", "inventory.settingsSuccess": "تنظیمات موجودی با موفقیت به‌روز شد.", "inventory.settingsError": "تنظیمات موجودی به‌روز نشد.",
    "inventory.ledgerTitle": "دفتر گردش موجودی", "inventory.ledgerHelp": "سابقه دائمی و قابل جستجوی دریافت، فروش، رزرو و اصلاحات.", "inventory.searchTransactions": "جستجوی محصول یا بارکد...", "inventory.allMovements": "همه انواع گردش", "inventory.fromDate": "از تاریخ", "inventory.toDate": "تا تاریخ", "inventory.date": "تاریخ", "inventory.beforeAfter": "قبل ← بعد", "inventory.noNote": "بدون یادداشت", "inventory.noTransactions": "گردشی با این فیلترها یافت نشد.", "inventory.transactionsError": "گردش‌های موجودی بارگذاری نشد.",
    "inventory.transaction.purchase": "دریافت موجودی", "inventory.transaction.sale": "فروش", "inventory.transaction.return": "برگشت مشتری", "inventory.transaction.adjustment": "اصلاح موجودی", "inventory.transaction.damaged": "آسیب‌دیده", "inventory.transaction.expired": "منقضی", "inventory.transaction.transfer": "انتقال", "inventory.transaction.reservation": "رزرو", "inventory.transaction.release": "آزادسازی رزرو",
};

export const inventoryPs: Record<keyof typeof inventoryEn, string> = {
    "inventory.title": "زېرمه", "inventory.subtitle": "د زېرمتون حالت وڅارئ، بدلونونه ثبت کړئ او محصولات پلور ته چمتو وساتئ.", "inventory.refresh": "نوی کول", "inventory.overview": "د زېرمتون لنډیز", "inventory.transactions": "راکړې ورکړې",
    "inventory.totalProducts": "ثبت شوي محصولات", "inventory.activeCount": "{count} فعال محصولات", "inventory.availableUnits": "شته واحدونه", "inventory.onHandCount": "ټول {count} واحدونه", "inventory.reservedUnits": "ساتل شوي واحدونه", "inventory.reservedHelp": "فعالو فرمایشونو ته ځانګړي شوي", "inventory.lowStock": "کمه زېرمه", "inventory.expiringCount": "{count} ژر پای ته رسېږي", "inventory.outOfStock": "له زېرمې وتلی", "inventory.needsAttention": "سمدستي پاملرنې ته اړتیا لري",
    "inventory.stockCatalog": "د زېرمتون لړلیک", "inventory.stockCatalogHelp": "خطر لرونکي محصولات لومړی ښودل کېږي.", "inventory.search": "محصول یا بارکوډ ولټوئ...", "inventory.allStock": "ټوله زېرمه", "inventory.healthy": "مناسب", "inventory.allCategories": "ټولې کټګورۍ", "inventory.sortRecent": "وروستي نوي شوي", "inventory.sortAvailable": "شته اندازه", "inventory.sortOnHand": "ټوله اندازه", "inventory.sortExpiry": "د پای نېټه", "inventory.sortName": "د محصول نوم", "inventory.stockStatus": "د زېرمتون حالت",
    "inventory.onHand": "ټول موجود", "inventory.reserved": "ساتل شوي", "inventory.available": "شته", "inventory.reorderPoint": "د بیا فرمایش حد", "inventory.expiryDate": "د پای نېټه", "inventory.noBarcode": "بارکوډ نشته", "inventory.loadError": "زېرمه پورته نه شوه.", "inventory.empty": "له دې فلټرونو سره محصول ونه موندل شو.", "inventory.adjustStock": "زېرمه بدله کړئ", "inventory.refreshing": "زېرمه نوې کېږي...", "inventory.expiringSoon": "ژر پای ته رسېږي",
    "inventory.adjustTitle": "د زېرمتون بدلون ثبت کړئ", "inventory.adjustDescription": "د بدلون لامل وټاکئ؛ بدلون به په تاریخچه کې ثبت شي.", "inventory.movementType": "د بدلون ډول", "inventory.quantity": "اندازه", "inventory.currentStock": "اوسنۍ زېرمه", "inventory.change": "بدلون", "inventory.newStock": "نوی ټولټال", "inventory.reservedGuard": "دا ایستل زېرمه د فرمایشونو له ساتل شوې اندازې کموي.", "inventory.note": "داخلي یادښت", "inventory.notePlaceholder": "د عرضه کوونکي شمېره، لامل یا ګټور معلومات ولیکئ...", "inventory.saving": "خوندي کېږي...", "inventory.confirmAdjustment": "بدلون ثبت کړئ", "inventory.adjustSuccess": "د زېرمتون بدلون په بریالیتوب ثبت شو.", "inventory.adjustError": "زېرمه بدله نه شوه.",
    "inventory.action.purchase": "زېرمه ترلاسه شوه", "inventory.action.purchaseHelp": "له عرضه کوونکي ترلاسه شوې زېرمه زیاته کړئ.", "inventory.action.return": "د پېرودونکي بېرته ستنول", "inventory.action.returnHelp": "د پلور وړ توکي بېرته زېرمتون ته واچوئ.", "inventory.action.addCorrection": "زیاتوونکی سمون", "inventory.action.addCorrectionHelp": "له فزیکي شمېرنې وروسته زېرمه زیاته کړئ.", "inventory.action.removeCorrection": "کموونکی سمون", "inventory.action.removeCorrectionHelp": "له فزیکي شمېرنې وروسته زېرمه کمه کړئ.", "inventory.action.damaged": "زیانمن توکي", "inventory.action.damagedHelp": "د نه پلور وړ توکي کم کړئ.", "inventory.action.expired": "پای ته رسېدلي توکي", "inventory.action.expiredHelp": "له نېټې تېر توکي کم کړئ.",
    "inventory.settingsTitle": "د زېرمتون امستنې", "inventory.settingsDescription": "د خبرتیا حد او اختیاري پای نېټه وټاکئ.", "inventory.reorderHelp": "کله چې شته اندازه دې حد ته ورسېږي، محصول کم‌زېرمه ښودل کېږي.", "inventory.expiryHelp": "که محصول د پای نېټه نه لري، تش یې پرېږدئ.", "inventory.settingsSuccess": "د زېرمتون امستنې په بریالیتوب نوې شوې.", "inventory.settingsError": "د زېرمتون امستنې نوې نه شوې.",
    "inventory.ledgerTitle": "د زېرمتون د بدلونونو تاریخچه", "inventory.ledgerHelp": "د ترلاسه کولو، پلور، ساتنې او سمونونو دایمي او د لټون وړ تاریخچه.", "inventory.searchTransactions": "محصول یا بارکوډ ولټوئ...", "inventory.allMovements": "د بدلون ټول ډولونه", "inventory.fromDate": "له نېټې", "inventory.toDate": "تر نېټې", "inventory.date": "نېټه", "inventory.beforeAfter": "مخکې ← وروسته", "inventory.noNote": "یادښت نشته", "inventory.noTransactions": "له دې فلټرونو سره بدلون ونه موندل شو.", "inventory.transactionsError": "د زېرمتون بدلونونه پورته نه شول.",
    "inventory.transaction.purchase": "زېرمه ترلاسه شوه", "inventory.transaction.sale": "پلور", "inventory.transaction.return": "د پېرودونکي ستنول", "inventory.transaction.adjustment": "د زېرمتون سمون", "inventory.transaction.damaged": "زیانمن", "inventory.transaction.expired": "پای ته رسېدلی", "inventory.transaction.transfer": "لېږد", "inventory.transaction.reservation": "ساتل شوی", "inventory.transaction.release": "ساتنه خوشې شوه",
};
