import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { FolderPlus, LoaderCircle, Pencil, Plus, ReceiptText, Save, Tags } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { useAdminAuth } from "@/features/auth/auth-context";
import { hasPermission, Permissions } from "@/features/auth/permissions";
import { operationKeys, useOperationQuery } from "@/features/operations/operations-hooks";
import { operationsService } from "@/features/operations/operations-service";
import type { ExpenseCategory } from "@/features/operations/operations-types";

const today = () => new Date().toISOString().slice(0, 10);
export default function ExpensesPage() {
  const qc = useQueryClient();
  const { user } = useAdminAuth();
  const canManage = hasPermission(user, Permissions.ExpensesManage);
  const { data: expenses, isLoading } = useOperationQuery(operationKeys.expenses, operationsService.expenses);
  const { data: categories, isLoading: categoriesLoading } = useOperationQuery(operationKeys.expenseCategories, operationsService.expenseCategories);
  const [tab, setTab] = useState<"expenses" | "categories">("expenses");
  const [expenseOpen, setExpenseOpen] = useState(false); const [categoryOpen, setCategoryOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [editingCategory, setEditingCategory] = useState<ExpenseCategory | null>(null);
  const [expense, setExpense] = useState({ expenseDate: today(), categoryId: 0, amount: 0, vendor: "", paymentMethod: "Cash", referenceNumber: "", description: "" });
  const [category, setCategory] = useState({ name: "", description: "", isActive: true });
  const openCategory = (item?: ExpenseCategory) => { if (!canManage) return; setEditingCategory(item ?? null); setCategory(item ? { name: item.name, description: item.description ?? "", isActive: item.isActive } : { name: "", description: "", isActive: true }); setCategoryOpen(true); };
  const saveExpense = async () => { if (!canManage) return; if (!expense.categoryId || expense.amount <= 0 || !expense.description.trim()) return toast.error("Category, amount, and description are required."); setSaving(true); try { await operationsService.createExpense({ ...expense, vendor: expense.vendor || null, referenceNumber: expense.referenceNumber || null }); await Promise.all([qc.invalidateQueries({ queryKey: operationKeys.expenses }), qc.invalidateQueries({ queryKey: operationKeys.summary })]); toast.success("Expense recorded."); setExpenseOpen(false); setExpense({ expenseDate: today(), categoryId: 0, amount: 0, vendor: "", paymentMethod: "Cash", referenceNumber: "", description: "" }); } catch (e) { toast.error(message(e)); } finally { setSaving(false); } };
  const saveCategory = async () => { if (!canManage) return; if (!category.name.trim()) return toast.error("Category name is required."); setSaving(true); try { await operationsService.saveExpenseCategory(editingCategory?.id ?? null, { ...category, description: category.description || null }); await qc.invalidateQueries({ queryKey: operationKeys.expenseCategories }); toast.success(editingCategory ? "Category updated." : "Category created."); setCategoryOpen(false); } catch (e) { toast.error(message(e)); } finally { setSaving(false); } };
  return <div className="space-y-6"><PageHeader title="Expenses" description="Track operating costs using reusable categories and clear payment references." actions={canManage ? <div className="flex gap-2"><Button variant="outline" onClick={() => openCategory()}><FolderPlus className="me-2 size-4" />New category</Button><Button onClick={() => setExpenseOpen(true)}><ReceiptText className="me-2 size-4" />New expense</Button></div> : undefined} />
    <div className="inline-flex rounded-lg border bg-muted/40 p-1"><Button size="sm" variant={tab === "expenses" ? "default" : "ghost"} onClick={() => setTab("expenses")}><ReceiptText className="me-2 size-4" />Expenses</Button><Button size="sm" variant={tab === "categories" ? "default" : "ghost"} onClick={() => setTab("categories")}><Tags className="me-2 size-4" />Categories</Button></div>
    {tab === "expenses" ? <Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Category</TableHead><TableHead>Description</TableHead><TableHead>Vendor</TableHead><TableHead>Method</TableHead><TableHead>Reference</TableHead><TableHead className="text-end">Amount</TableHead></TableRow></TableHeader><TableBody>{isLoading ? <Loading colSpan={7} /> : expenses?.length ? expenses.map(x => <TableRow key={x.id}><TableCell>{date(x.expenseDate)}</TableCell><TableCell><Badge variant="outline">{x.categoryName}</Badge></TableCell><TableCell className="max-w-md"><p className="truncate">{x.description}</p></TableCell><TableCell>{x.vendor ?? "—"}</TableCell><TableCell>{x.paymentMethod}</TableCell><TableCell>{x.referenceNumber ?? "—"}</TableCell><TableCell className="text-end font-semibold">{money(x.amount)}</TableCell></TableRow>) : <Empty colSpan={7} text="No expenses have been recorded." />}</TableBody></Table></CardContent></Card>
    : <Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Category</TableHead><TableHead>Description</TableHead><TableHead>Status</TableHead><TableHead className="w-20"></TableHead></TableRow></TableHeader><TableBody>{categoriesLoading ? <Loading colSpan={4} /> : categories?.length ? categories.map(x => <TableRow key={x.id}><TableCell className="font-medium">{x.name}</TableCell><TableCell>{x.description ?? "—"}</TableCell><TableCell><Badge variant={x.isActive ? "default" : "outline"}>{x.isActive ? "Active" : "Inactive"}</Badge></TableCell><TableCell>{canManage && <Button size="icon" variant="ghost" onClick={() => openCategory(x)}><Pencil className="size-4" /></Button>}</TableCell></TableRow>) : <Empty colSpan={4} text="No expense categories exist." />}</TableBody></Table></CardContent></Card>}
    <Dialog open={expenseOpen} onOpenChange={setExpenseOpen}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>Record expense</DialogTitle><DialogDescription>Add a categorized business cost to the operational ledger.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label="Expense date"><Input type="date" value={expense.expenseDate} onChange={e => setExpense(x => ({ ...x, expenseDate: e.target.value }))} /></Field><Field label="Category *"><select className="h-9 w-full rounded-md border bg-background px-3" value={expense.categoryId} onChange={e => setExpense(x => ({ ...x, categoryId: Number(e.target.value) }))}><option value={0}>Select category</option>{categories?.filter(x => x.isActive).map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Amount *"><Input type="number" min={0.01} step="0.01" value={expense.amount} onChange={e => setExpense(x => ({ ...x, amount: Number(e.target.value) }))} /></Field><Field label="Vendor / paid to"><Input value={expense.vendor} onChange={e => setExpense(x => ({ ...x, vendor: e.target.value }))} /></Field><Field label="Payment method"><select className="h-9 w-full rounded-md border bg-background px-3" value={expense.paymentMethod} onChange={e => setExpense(x => ({ ...x, paymentMethod: e.target.value }))}><option>Cash</option><option>Card</option><option>Bank transfer</option><option>Mobile money</option></select></Field><Field label="Reference"><Input value={expense.referenceNumber} onChange={e => setExpense(x => ({ ...x, referenceNumber: e.target.value }))} /></Field><div className="sm:col-span-2"><Field label="Description *"><Textarea rows={4} value={expense.description} onChange={e => setExpense(x => ({ ...x, description: e.target.value }))} /></Field></div></div><DialogFooter><Button variant="outline" onClick={() => setExpenseOpen(false)}>Cancel</Button><Button onClick={saveExpense} disabled={saving}>{saving ? <LoaderCircle className="me-2 size-4 animate-spin" /> : <Save className="me-2 size-4" />}Save expense</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={categoryOpen} onOpenChange={setCategoryOpen}><DialogContent><DialogHeader><DialogTitle>{editingCategory ? "Edit expense category" : "New expense category"}</DialogTitle><DialogDescription>Categories make expense reporting consistent.</DialogDescription></DialogHeader><div className="space-y-4"><Field label="Category name *"><Input value={category.name} onChange={e => setCategory(x => ({ ...x, name: e.target.value }))} /></Field><Field label="Description"><Textarea value={category.description} onChange={e => setCategory(x => ({ ...x, description: e.target.value }))} /></Field><label className="flex items-center gap-3"><Checkbox checked={category.isActive} onCheckedChange={v => setCategory(x => ({ ...x, isActive: v === true }))} />Active category</label></div><DialogFooter><Button variant="outline" onClick={() => setCategoryOpen(false)}>Cancel</Button><Button onClick={saveCategory} disabled={saving}>{editingCategory ? <Save className="me-2 size-4" /> : <Plus className="me-2 size-4" />}Save category</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function Loading({ colSpan }: { colSpan: number }) { return <TableRow><TableCell colSpan={colSpan} className="h-32 text-center"><LoaderCircle className="mx-auto size-5 animate-spin" /></TableCell></TableRow>; }
function Empty({ colSpan, text }: { colSpan: number; text: string }) { return <TableRow><TableCell colSpan={colSpan} className="h-32 text-center text-muted-foreground">{text}</TableCell></TableRow>; }
function money(value: number) { return new Intl.NumberFormat(undefined, { style: "currency", currency: "USD" }).format(value); }
function date(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
function message(error: unknown) { return (error as { response?: { data?: { message?: string } }; message?: string }).response?.data?.message ?? (error as Error).message ?? "The operation failed."; }
