import { useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { Banknote, LoaderCircle, Pencil, Plus, Save, Trash2, UserRoundPlus, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { ConfirmActionDialog } from "@/components/confirm-action-dialog";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { useAdminAuth } from "@/features/auth/auth-context";
import { hasPermission, Permissions } from "@/features/auth/permissions";
import { operationKeys, useOperationQuery } from "@/features/operations/operations-hooks";
import { operationsService } from "@/features/operations/operations-service";
import type { Staff } from "@/features/operations/operations-types";

const today = () => new Date().toISOString().slice(0, 10);
const current = new Date();
const blankStaff = { employeeNumber: "", fullName: "", phone: "", email: "", position: "", department: "", hireDate: today(), baseSalary: 0, isActive: true, address: "", notes: "" };
export default function StaffPage() {
  const qc = useQueryClient();
  const { user } = useAdminAuth();
  const canManageStaff = hasPermission(user, Permissions.StaffManage);
  const canViewPayroll = hasPermission(user, Permissions.PayrollView);
  const canManagePayroll = hasPermission(user, Permissions.PayrollManage);
  const { data: staff, isLoading } = useOperationQuery(operationKeys.staff, operationsService.staff);
  const { data: salaries, isLoading: salariesLoading } = useOperationQuery(operationKeys.salaries, operationsService.salaries, canViewPayroll);
  const [tab, setTab] = useState<"staff" | "salary">("staff");
  const [staffOpen, setStaffOpen] = useState(false); const [salaryOpen, setSalaryOpen] = useState(false); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState<number | null>(null);
  const [editing, setEditing] = useState<Staff | null>(null);
  const [form, setForm] = useState(blankStaff);
  const [salary, setSalary] = useState({ staffId: 0, periodYear: current.getFullYear(), periodMonth: current.getMonth() + 1, bonus: 0, deduction: 0, paidDate: today(), paymentMethod: "Cash", referenceNumber: "", notes: "" });
  const selectedStaff = useMemo(() => staff?.find(x => x.id === salary.staffId), [staff, salary.staffId]);
  const netSalary = Math.max(0, (selectedStaff?.baseSalary ?? 0) + salary.bonus - salary.deduction);
  const openCreate = () => { if (!canManageStaff) return; setEditing(null); setForm(blankStaff); setStaffOpen(true); };
  const openEdit = (item: Staff) => { if (!canManageStaff) return; setEditing(item); setForm({ employeeNumber: item.employeeNumber, fullName: item.fullName, phone: item.phone ?? "", email: item.email ?? "", position: item.position ?? "", department: item.department ?? "", hireDate: item.hireDate, baseSalary: item.baseSalary, isActive: item.isActive, address: item.address ?? "", notes: item.notes ?? "" }); setStaffOpen(true); };
  const saveStaff = async () => { if (!canManageStaff) return; if (!form.employeeNumber.trim() || !form.fullName.trim()) return toast.error("Employee number and full name are required."); setSaving(true); try { await operationsService.saveStaff(editing?.id ?? null, { ...form, phone: form.phone || null, email: form.email || null, position: form.position || null, department: form.department || null, address: form.address || null, notes: form.notes || null }); await qc.invalidateQueries({ queryKey: operationKeys.staff }); toast.success(editing ? "Staff member updated." : "Staff member created."); setStaffOpen(false); } catch (e) { toast.error(message(e)); } finally { setSaving(false); } };
  const remove = async (id: number) => { if (!canManageStaff) return; setDeleting(id); try { await operationsService.deleteStaff(id); await qc.invalidateQueries({ queryKey: operationKeys.staff }); toast.success("Staff member removed."); } catch (e) { toast.error(message(e)); throw e; } finally { setDeleting(null); } };
  const saveSalary = async () => { if (!canManagePayroll) return; if (!salary.staffId) return toast.error("Select a staff member."); setSaving(true); try { await operationsService.createSalary({ ...salary, referenceNumber: salary.referenceNumber || null, notes: salary.notes || null }); await Promise.all([qc.invalidateQueries({ queryKey: operationKeys.salaries }), qc.invalidateQueries({ queryKey: operationKeys.summary })]); toast.success("Salary payment recorded."); setSalaryOpen(false); setSalary(x => ({ ...x, staffId: 0, bonus: 0, deduction: 0, referenceNumber: "", notes: "" })); } catch (e) { toast.error(message(e)); } finally { setSaving(false); } };
  return <div className="space-y-6"><PageHeader title="Staff and payroll" description="Maintain staff profiles, salaries, bonuses, deductions, and monthly payment history." actions={(canManagePayroll || canManageStaff) ? <div className="flex gap-2">{canManagePayroll && <Button variant="outline" onClick={() => setSalaryOpen(true)}><Banknote className="me-2 size-4" />Pay salary</Button>}{canManageStaff && <Button onClick={openCreate}><UserRoundPlus className="me-2 size-4" />New staff</Button>}</div> : undefined} />
    <div className="inline-flex rounded-lg border bg-muted/40 p-1"><Button size="sm" variant={tab === "staff" ? "default" : "ghost"} onClick={() => setTab("staff")}><UsersRound className="me-2 size-4" />Staff</Button>{canViewPayroll && <Button size="sm" variant={tab === "salary" ? "default" : "ghost"} onClick={() => setTab("salary")}><Banknote className="me-2 size-4" />Salary history</Button>}</div>
    {tab === "staff" ? <Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Employee</TableHead><TableHead>Position</TableHead><TableHead>Department</TableHead><TableHead>Contact</TableHead><TableHead className="text-end">Base salary</TableHead><TableHead>Status</TableHead><TableHead className="w-28"></TableHead></TableRow></TableHeader><TableBody>{isLoading ? <Loading colSpan={7} /> : staff?.length ? staff.map(x => <TableRow key={x.id}><TableCell><p className="font-medium">{x.fullName}</p><p className="text-xs text-muted-foreground">{x.employeeNumber}</p></TableCell><TableCell>{x.position ?? "—"}</TableCell><TableCell>{x.department ?? "—"}</TableCell><TableCell><p>{x.phone ?? "—"}</p><p className="text-xs text-muted-foreground">{x.email}</p></TableCell><TableCell className="text-end">{money(x.baseSalary)}</TableCell><TableCell><Badge variant={x.isActive ? "default" : "outline"}>{x.isActive ? "Active" : "Inactive"}</Badge></TableCell><TableCell>{canManageStaff && <div className="flex justify-end"><Button size="icon" variant="ghost" onClick={() => openEdit(x)}><Pencil className="size-4" /></Button><ConfirmActionDialog trigger={<Button size="icon" variant="ghost"><Trash2 className="size-4 text-destructive" /></Button>} title="Remove staff member?" description="The profile will be archived. Existing salary history remains available." confirmLabel="Remove" destructive pending={deleting === x.id} onConfirm={() => remove(x.id)} /></div>}</TableCell></TableRow>) : <Empty colSpan={7} text="No staff members have been added." />}</TableBody></Table></CardContent></Card>
    : <Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Staff</TableHead><TableHead>Period</TableHead><TableHead>Paid date</TableHead><TableHead className="text-end">Base</TableHead><TableHead className="text-end">Bonus</TableHead><TableHead className="text-end">Deduction</TableHead><TableHead className="text-end">Net paid</TableHead><TableHead>Method</TableHead></TableRow></TableHeader><TableBody>{salariesLoading ? <Loading colSpan={8} /> : salaries?.length ? salaries.map(x => <TableRow key={x.id}><TableCell className="font-medium">{x.staffName}</TableCell><TableCell>{monthName(x.periodMonth)} {x.periodYear}</TableCell><TableCell>{date(x.paidDate)}</TableCell><TableCell className="text-end">{money(x.baseSalary)}</TableCell><TableCell className="text-end text-emerald-600">+{money(x.bonus)}</TableCell><TableCell className="text-end text-destructive">-{money(x.deduction)}</TableCell><TableCell className="text-end font-semibold">{money(x.netAmount)}</TableCell><TableCell>{x.paymentMethod}</TableCell></TableRow>) : <Empty colSpan={8} text="No salary payments have been recorded." />}</TableBody></Table></CardContent></Card>}
    <Dialog open={staffOpen} onOpenChange={setStaffOpen}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{editing ? "Edit staff member" : "New staff member"}</DialogTitle><DialogDescription>Keep employment and salary information together.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label="Employee number *"><Input value={form.employeeNumber} onChange={e => setForm(x => ({ ...x, employeeNumber: e.target.value }))} /></Field><Field label="Full name *"><Input value={form.fullName} onChange={e => setForm(x => ({ ...x, fullName: e.target.value }))} /></Field><Field label="Position"><Input value={form.position} onChange={e => setForm(x => ({ ...x, position: e.target.value }))} /></Field><Field label="Department"><Input value={form.department} onChange={e => setForm(x => ({ ...x, department: e.target.value }))} /></Field><Field label="Phone"><Input value={form.phone} onChange={e => setForm(x => ({ ...x, phone: e.target.value }))} /></Field><Field label="Email"><Input type="email" value={form.email} onChange={e => setForm(x => ({ ...x, email: e.target.value }))} /></Field><Field label="Hire date"><Input type="date" value={form.hireDate} onChange={e => setForm(x => ({ ...x, hireDate: e.target.value }))} /></Field><Field label="Base salary"><Input type="number" min={0} step="0.01" value={form.baseSalary} onChange={e => setForm(x => ({ ...x, baseSalary: Number(e.target.value) }))} /></Field><div className="sm:col-span-2"><Field label="Address"><Textarea value={form.address} onChange={e => setForm(x => ({ ...x, address: e.target.value }))} /></Field></div><div className="sm:col-span-2"><Field label="Notes"><Textarea value={form.notes} onChange={e => setForm(x => ({ ...x, notes: e.target.value }))} /></Field></div><label className="flex items-center gap-3"><Checkbox checked={form.isActive} onCheckedChange={v => setForm(x => ({ ...x, isActive: v === true }))} />Active staff member</label></div><DialogFooter><Button variant="outline" onClick={() => setStaffOpen(false)}>Cancel</Button><Button onClick={saveStaff} disabled={saving}>{saving ? <LoaderCircle className="me-2 size-4 animate-spin" /> : <Save className="me-2 size-4" />}Save staff</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={salaryOpen} onOpenChange={setSalaryOpen}><DialogContent><DialogHeader><DialogTitle>Record salary payment</DialogTitle><DialogDescription>One payment is allowed per staff member and salary month.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label="Staff member *"><select className="h-9 w-full rounded-md border bg-background px-3" value={salary.staffId} onChange={e => setSalary(x => ({ ...x, staffId: Number(e.target.value) }))}><option value={0}>Select staff</option>{staff?.filter(x => x.isActive).map(x => <option key={x.id} value={x.id}>{x.fullName} · {money(x.baseSalary)}</option>)}</select></Field><Field label="Paid date"><Input type="date" value={salary.paidDate} onChange={e => setSalary(x => ({ ...x, paidDate: e.target.value }))} /></Field><Field label="Year"><Input type="number" min={2000} value={salary.periodYear} onChange={e => setSalary(x => ({ ...x, periodYear: Number(e.target.value) }))} /></Field><Field label="Month"><select className="h-9 w-full rounded-md border bg-background px-3" value={salary.periodMonth} onChange={e => setSalary(x => ({ ...x, periodMonth: Number(e.target.value) }))}>{Array.from({ length: 12 }, (_, i) => <option key={i + 1} value={i + 1}>{monthName(i + 1)}</option>)}</select></Field><Field label="Bonus"><Input type="number" min={0} step="0.01" value={salary.bonus} onChange={e => setSalary(x => ({ ...x, bonus: Number(e.target.value) }))} /></Field><Field label="Deduction"><Input type="number" min={0} step="0.01" value={salary.deduction} onChange={e => setSalary(x => ({ ...x, deduction: Number(e.target.value) }))} /></Field><Field label="Payment method"><select className="h-9 w-full rounded-md border bg-background px-3" value={salary.paymentMethod} onChange={e => setSalary(x => ({ ...x, paymentMethod: e.target.value }))}><option>Cash</option><option>Bank transfer</option><option>Mobile money</option></select></Field><Field label="Reference"><Input value={salary.referenceNumber} onChange={e => setSalary(x => ({ ...x, referenceNumber: e.target.value }))} /></Field><div className="sm:col-span-2 rounded-lg border bg-muted/40 p-4"><div className="flex justify-between"><span>Base salary</span><strong>{money(selectedStaff?.baseSalary ?? 0)}</strong></div><div className="mt-2 flex justify-between text-lg"><span>Net payment</span><strong>{money(netSalary)}</strong></div></div><div className="sm:col-span-2"><Field label="Notes"><Textarea value={salary.notes} onChange={e => setSalary(x => ({ ...x, notes: e.target.value }))} /></Field></div></div><DialogFooter><Button variant="outline" onClick={() => setSalaryOpen(false)}>Cancel</Button><Button onClick={saveSalary} disabled={saving}><Plus className="me-2 size-4" />Record payment</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function Loading({ colSpan }: { colSpan: number }) { return <TableRow><TableCell colSpan={colSpan} className="h-32 text-center"><LoaderCircle className="mx-auto size-5 animate-spin" /></TableCell></TableRow>; }
function Empty({ colSpan, text }: { colSpan: number; text: string }) { return <TableRow><TableCell colSpan={colSpan} className="h-32 text-center text-muted-foreground">{text}</TableCell></TableRow>; }
function money(value: number) { return new Intl.NumberFormat(undefined, { style: "currency", currency: "USD" }).format(value); }
function date(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
function monthName(month: number) { return new Intl.DateTimeFormat(undefined, { month: "long", timeZone: "UTC" }).format(new Date(Date.UTC(2026, month - 1, 1))); }
function message(error: unknown) { return (error as { response?: { data?: { message?: string } }; message?: string }).response?.data?.message ?? (error as Error).message ?? "The operation failed."; }
